### ISSUE TITLE
Question about language fall back in Model Admin

### ISSUE THREAD

**Issue by dio5** [tractorcow-farm/silverstripe-fluent#102]
Am I right in thinking that for DataObjects in ModelAdmin the falling back to the default language is not there?

I.e if you manage a dataobject through a gridfield on pages, you'll see fields falling back to the default values (as described here https://github.com/tractorcow/silverstripe-fluent/blob/3.1/docs/en/how-fluent-works.md in 'Creating translations'). But for dataobjects on ModelAdmin, this is not the case and you get blank fields? 

At least that's the behaviour I'm seeing. Just a question really more than an issue :)

**Comment by dio5** [comment]
So to come back to this.

I've noticed that on dataobjects managed directly under modeladmin, it seems that the base field is always overwritten, regardless of the locale, so depending on which one you save last, that will be the value in the base field.

I thought it had to do with line 586-596 here https://github.com/tractorcow/silverstripe-fluent/blob/3.1/code/extensions/FluentExtension.php, but apparently $updates['fields'][$defaultField] is never being set (even on pages or objects managed through gridfield on pages), you always get a undefined index error if you try to debug that value right before line 590.

It doesn't seem to have implications on the frontend as long as you have values in all languages, but it's really weird why it does override the base field only in objects managed directly under modeladmin (so not even in objects that are relations from modeladmin managed objects)

**Comment by dio5** [comment]
And obviously I've found exceptions to it as well... Really odd!

**Comment by tractorcow** [comment]
Yeah, this code took quite a bit of evolution to get working, and it relies on sparsely documented behaviour of the DB manipulations. That code should prevent updates to the non-default locale overriding the default locale data.

If you have a base field with a value (that isn't null) it should not be overwritten.

I'd be interested to know what's in `$updates['fields'][$defaultField]` in the cases where it IS overwritten.

**Comment by dio5** [comment]
Yeah I tried to find that out but when I tried to debug it I always got the undefined index error on $updates['fields'][$defaultField] - so it's not being set somehow.

**Comment by dio5** [comment]
So as far as I could see the line 594 is never being run (even though the base field has value).

**Comment by tractorcow** [comment]
What does the DB row look like prior to and after a write (where the default value is overwritten, when it shouldn't be)?

**Comment by dio5** [comment]
Well suppose you have 

Title, Title_en_GB, Title_de_DE

Initially:

'My Title', '', ''

If you save English

'My Title EN', 'My Title EN', ''

if you save German

'My Title DE', 'My Title EN', 'My Title DE'

if you then save English again with a different value

'My Title EN different', 'My Title EN different', 'My Title DE'

**Comment by dio5** [comment]
My point here is that my base field always ends up with the value of the language I last saved (when it's different) rather than having the default lang value, and for some weird reason it's not doing that on anything in the Pages section, and not even on everything in ModelAdmin. It doesn't really influence the actual use so it's not a problem but it did strike me as something weird :)

**Comment by tractorcow** [comment]
There could be a bug in FluentExtension::onBeforeWrite. Perhaps debugging the $changed fields during augmentWrite would reveal the solution? If the Title_en_GB isn't correctly marked as changed during the write, that would mean it gets left out of the $manipulation, meaning that the current value of Title (whatever locale you're in) would overwrite the default field in the DB.

**Comment by tractorcow** [comment]
can you Debug::dump the $manipulation prior to and after the final write? (the one that overwrites the default field in german, but shouldn't?)

**Comment by dio5** [comment]
Yeah I'll have a go at that. Not sure at what point I'll get to it though but I'll let you know my findings.

**Comment by dio5** [comment]
So here's what I got..  (with the fields Name, Name_en_GB and Name_de_DE in db)

Saving German with a new value:
Before the foreach line 570

```
====================================================================================================
FluentExtension.php:567 - FluentExtension::augmentWrite()

Array
(
    [DateAssetCategory] => Array
        (
            [fields] => Array
                (
                    [Name] => 'Name DE'
                    [LastEdited] => '2015-01-21 09:25:49'
                )

            [command] => update
            [id] => 3
        )

)

====================================================================================================
```
After (line 605):
```
====================================================================================================
FluentExtension.php:605 - FluentExtension::augmentWrite()

Array
(
    [DateAssetCategory] => Array
        (
            [fields] => Array
                (
                    [Name] => 'Name DE'
                    [LastEdited] => '2015-01-21 09:25:49'
                    [Name_de_DE] => 'Name DE'
                )

            [command] => update
            [id] => 3
        )

)

====================================================================================================
```

So it looks to me that the default is not in there. I've compared to some dataobjects in modeladmin that do work and they do have the default in there so something is causing those faulty dataobject to not have it. I'll investigate a bit more.

**Comment by tractorcow** [comment]
At least the source of the problem is a bit clearer. We can always fallback
to this->owner->Name_en_GB perhaps?

**Comment by dio5** [comment]
I just noticed that the modeladmin objects I thought and I'm sure were functioning alright, do get it as well - though I defly had moments were they did work, which is really odd. Anyway I'm not gonna worry about it for now, but I'll get back to this if it should become a problem.

**Comment by bigbang1980** [comment]
I'm using fluent (Persian & English) and having problem with gridfield (using Data object)
when i enter data in cms only one language shows in website.
how i can fix fluent with gridfield

<?php
class ProductDetail extends DataObject {
    private static $db = array(
        'ProductName' => 'Varchar',
        'ProductDes' => 'text',
        'ProductURL' => 'text',
    );
    private static $has_one = array(
        'ProductImage' => 'Image',
        'Product' => 'Product',
    );   

    private static $summary_fields = array(
        'GridThumbnail' => 'تصویر محصول',
        'ProductName' => 'نام محصول',
        'ProductDes' => 'توضیحات',
    );
    public function getGridThumbnail() {
        if($this->ProductImage()->exists()) {
            return $this->ProductImage()->SetWidth(200);
        }
    }     


	public function getCMSFields() {
        $fields = FieldList::create(
        	TextField::create('ProductName','نام محصول'),
        	TextAreaField::create('ProductDes','توضیحات محصول'),
        	TextField::create('ProductURL','آدرس صفحه محصول'),
        	UploadField::create('ProductImage','تصویر محصول')
        	);
        return $fields;
    }

}

**Comment by tractorcow** [comment]
Hi @bigbang1980 did you add the FluentExtension to ProductDetail?

**Comment by bigbang1980** [comment]
how can i add FluentExtension?

**Comment by bigbang1980** [comment]
i add this to config.yml :
SiteTree:
  extensions:
    - 'FluentFilteredExtension'

**Comment by tractorcow** [comment]
Yes, that adds it to the SiteTree, and you need to add it to ProductDetail as well.

```yml
ProductDetail:
  extensions:
    - FluentExtension
```
