### ISSUE TITLE
Fulltext search issues

### ISSUE THREAD

**Issue by tractorcow** [tractorcow-farm/silverstripe-fluent#11]
Need to ensure that fulltext search is working on the correct locale

**Comment by sunnysideup** [comment]
hi @tractorcow , I cant make the search work.  Is there any special setting I need to turn on? 

I am a bit lost on how the code works.

Thank you

Nicolaas

**Comment by sunnysideup** [comment]
i have this turned on of course:

```

Fluent:
  search_adapters:
    MySQLDatabase: FluentMySQLSearch

```

**Comment by tractorcow** [comment]
Hi @sunnysideup it should work out of the box, assuming you have normal site search enabled.

Can you see if FluentMySQLSearch::augmentSearch is invoked during search? The next step is to make sure it re-writes the search properly. :D

This hooks into parts of MySQLDatabase::searchEngine, so I'd expect that if your default search uses this the appropriate hook is invoked.

**Comment by sunnysideup** [comment]
Hi Damian

I think I have worked it out.  It appears that because we internationalised ShowInSearch, the original ShowInSearch field always stayed FALSE.  

Thank you for having a look at this.
