### ISSUE TITLE
Show full locale in the 'badges'

### ISSUE THREAD

**Issue by JorisDebonnet** [tractorcow-farm/silverstripe-fluent#389]
Commit e75cbc1d has introduced a badge showing part of the locale next to the Page Title. That's nice to have, but it only shows the suffix, e.g. NZ or US. That is useful when you have localized pages such as en_NZ and en_US, but is rather useless when using _translated_ pages that may have the same country component, such as en_CA and fr_CA, or nl_BE and fr_BE. 

Possible solutions: 
1. Show the whole locale instead of just the country part
2. Show the locale URLSegment instead
3. Make it a config (locale / language / country / urlsegment / ?)

I can make the change if we can agree on option 1 or 2. 
I personally suggest 1, as I don't think it will hurt anyone, and it is the most informative. But option 2 could be a good compromise because it likely focuses on whatever the developer is using Fluent for.

**Comment by robbieaverill** [comment]
We suspected this might be a problem. Currently the templates on the frontend are doing a similar thing too.

I'd be in favour of option 3, or provide an extension point to update the formatting for what gets used in the badge.

We want to keep the badge small if possible, and recognise that some users will have different requirements.

How would that sit with you?

**Comment by JorisDebonnet** [comment]
I would prefer a config to an extension point then (or both; perhaps people want to put little flags), but in any case those options seem like a little too much work for myself to work on :)

**Comment by clarkepaul** [comment]
Question, what does the URLSegment output generally? 
Option 1 seems like a good incremental improvement, I think there would enough space for en_CA (even though its not as visually pleasing its more informative), but I it sound like if we would do it properly then it should be dev defined with opt. 3 as it provides the most flexibility.

**Comment by JorisDebonnet** [comment]
The reason I added option 2 with the URLSegment is because this is in itself already a user-defined abbreviation for the locale. In that sense, it could serve as the badge as well. By default it is the locale itself (e.g. `/en_US/`) but if a website focusses on localization within one language, the admin will likely use something like `/us/` and `/nz/`, while websites focussing on languages will likely have something like `/en/` and `/nl/`.

I agree 3 has the most flexibility, but top flexibility is not "necessarily" the best option because it adds complexity. If we believe option 2 could serve all cases, I believe it should be considered. Can someone argue in which situation option 2 would not suffice? (perhaps in conjunction with an extension point, as @robbieaverill suggested)

**Comment by ninty9notout** [comment]
@JorisDebonnet I only saw this now. I've come across the same problem with `cy_GB` and `en_GB`. [My solution](https://github.com/tractorcow/silverstripe-fluent/pull/416) was to introduce a flag in fluent which would let the developer specify if they'd like to use the full title i.e. `Welsh` or just the suffix by default i.e. `GB`. The title, obviously is the locale title you setup.

I felt this solution was the least difficult and more straight to the point. Maybe it will solve your problem, too.

**Comment by bummzack** [comment]
I've hit the same problem and found this issue. I like the config idea, but what about using a template instead? You could pass the classes, tooltip and the locale to the template and then developers are free to pick whatever information from the `Locale` that they want to display.

**Comment by robbieaverill** [comment]
PR at https://github.com/tractorcow-farm/silverstripe-fluent/pull/510

**Comment by ScopeyNZ** [comment]
#510 is merged. I think that's an acceptable solution. Feel free to re-open if there's further suggestions.

**Comment by JorisDebonnet** [comment]
The only thing I still wonder is whether is whether `getLocaleSuffix` is a sensible default ... After all, it doesn't work for the example that appears in the README either, since it uses the example of en_NZ and mi_NZ, which will both show a NZ label by default.

I would therefore suggest adding one commit to this fix, to make the default into URLSegment (as I did [in my fork](https://github.com/JorisDebonnet/silverstripe-fluent/commit/961607a3f73fd209328ecf1ab47090ffb58408d1)). I feel like that can never be misunderstood, improving the user experience, and then it can always be made more pretty by developers using `updateBadgeLabel`.

**Comment by robbieaverill** [comment]
Sure, makes sense. Would you like to make a PR?

**Comment by JorisDebonnet** [comment]
Done, see #517.
