### ISSUE TITLE
Issue with HtmlEditorField in Page which extends SiteTree

### ISSUE THREAD

**Issue by sum-github** [tractorcow-farm/silverstripe-fluent#412]
Hi everyone!

I got 2 languages in my project.  I have customized field "Intro" in the page class. Saving an HTMLText field (Intro) in default locale (English) all is ok. When I switch to the second language and try to edit/save the intro field by inputting german language, the field shows the English content but the German is being saved in the database.

I am using fluent version 3.2 with SilverStripe 3.1.10

Any suggestions?

Thanks in advance.

**Comment by sum-github** [comment]
Page.php and fluent.yml are attached.

[page-php.txt](https://github.com/tractorcow/silverstripe-fluent/files/2001650/page-php.txt)
[fluent-yml.txt](https://github.com/tractorcow/silverstripe-fluent/files/2001654/fluent-yml.txt)

**Comment by thezenmonkey** [comment]
Any movement not this?

**Comment by ScopeyNZ** [comment]
Hey @thezenmonkey. Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

I am aware of sites using Fluent with dozens of locales that aren't having an issue with HtmlEditorField. I'm going to close this issue but I'm open to re-opening it if it can be validated on SilverStripe 4 with the latest version of Fluent.

Sorry I couldn't be of more help!
