### ISSUE TITLE
Fluent sends cookies by default, preventing HTTP caching in most layers

### ISSUE THREAD

**Issue by chillu** [tractorcow-farm/silverstripe-fluent#440]
`Set-Cookie: FluentLocale=deleted` gets added to a default response (e.g. in the CWP 2.x recipe). That's killing caching, since most CDNs won't cache if cookie values are present, regardless what `Cache-Control` says. This might sound like a small thing, but cachability is a major focus of the upcoming CWP 2.1 release, so I consider this a high impact bug.

**Comment by robbieaverill** [comment]
cc @tractorcow, I don't know much about the context for this

**Comment by dhensby** [comment]
Have you found the source @chillu? I think this must be an easy fix?

**Comment by chillu** [comment]
@dhensby See https://github.com/tractorcow/silverstripe-fluent/pull/442

**Comment by chillu** [comment]
@robbieaverill @tractorcow I can't reproduce the test failures in https://travis-ci.org/tractorcow/silverstripe-fluent/jobs/406075939 locally, when reproducing the Travis build steps. The only difference I can see is that I'm running PHP 7.2 rather than 7.0
