### ISSUE TITLE
v4: Proposal for UX changes to "copy" interface/s

### ISSUE THREAD

**Issue by chrispenny** [tractorcow-farm/silverstripe-fluent#444]
## The problem
We've now had a bit of experience with real content authors, and they had been finding that sometimes the result of a "copy" was not what they expected.

### Not what they expected?
In our current project, we have a large number of Locales and a large number of Fallbacks. When viewing an un-localised page, it's often not immediately obvious what your content will be when you hit the "copy to draft" of "copy & publish" buttons (especially if your content is contained within Content Blocks).

## Our solution / proposal
To make this interaction more clear for our authors, we have completely removed the "copy" actions from all un-localised pages, and we have instead created an interface to "transfer to locale" ("copy to locale" might be better wording).

Now when you visit an un-localised Page, you get a Page in read-only, with no actions.

Germany is currently un-localised:
<img width="973" alt="screen shot 2018-07-20 at 10 12 15 am" src="https://user-images.githubusercontent.com/505788/42973150-30bcd64c-8c06-11e8-847c-c1b3fba4d8f1.png">

In order to move content into this Locale, you must now visit an already localised Page, and use the "transfer to locale" interface.

International **is** localised:
<img width="973" alt="screen shot 2018-07-20 at 10 13 05 am" src="https://user-images.githubusercontent.com/505788/42973158-396de8ee-8c06-11e8-9110-291db7121e31.png">

The drop down list provided has two groups, "create" for Locales that don't already have a localisation, and "override" for when a localisation already exists in that Locale.
<img width="189" alt="screen shot 2018-07-20 at 10 13 18 am" src="https://user-images.githubusercontent.com/505788/42973181-576c1ac8-8c06-11e8-9d9d-c54890c9992b.png">

After the "copy" has been performed, you will have a draft saved in that Locale.
<img width="972" alt="screen shot 2018-07-20 at 10 19 46 am" src="https://user-images.githubusercontent.com/505788/42973232-89f6ecfc-8c06-11e8-8a0d-d6e09fe5a9e1.png">

## Conclusion

Content authors are now forced to view the Locale that contains the content that they are interested in copying. This removes any ambiguity around where the content comes from when a Locale has multiple Fallbacks.

This also provides a faster way to override existing content in a Locale with content from another Locale.

It will take me a while to move this from project code to the module, so I'm keen to hear your thoughts first :)

**Comment by ScopeyNZ** [comment]
> It will take me a while to move this from project code to the module, so I'm keen to hear your thoughts first.

Makes sense to me. I guess this is something related to your site but the notice message indicates the user should "make use of one of the 'copy' actions provided below" but there are no copy actions by default?

**Comment by chrispenny** [comment]
Right, sorry, I forgot that that was project code (I've been looking at this same project for the last 8 month..): We had renamed the "Save draft" and "Publish" buttons to "Copy to draft" and "Copy & publish" for Pages that had not yet been localised.

I think it would be worthwhile for me to document the current Fluent behaviour (for my own sake as well). This is undoubtedly going to change that behaviour, so, seeing both side by side might be useful in our decision.

**Comment by tractorcow** [comment]
This feature is now superseded by the new cross-locale menu (currently available on `develop` branch, will be 5.0 alpha soonish).
