### ISSUE TITLE
v4: Fluent Filtered applied even in stage=Stage.

### ISSUE THREAD

**Issue by chrispenny** [tractorcow-farm/silverstripe-fluent#461]
We have some time soon to implement a solution, but I'd like to know what the preference is.

## The problem

You have a project where `frontend_publish_required` is set to `false`, as you want to be able to display Pages on the frontend using inherited content.

`FluentFilteredExtension` is then used to control when you do or don't want to see a particular Page in a particular Locale (sometimes you **don't** want to display inherited content on the frontend for a particular Locale).

The issue is when you have purposefully not added a Filtered Locale, but you want to start drafting the Page in that Locale. Because `FluentFilteredExtension::augmentSQL()` is applied anytime you are viewing the Frontend (regardless or reading mode), you cannot use the "preview" panel, or view it on the frontend with `stage=Stage`. You are forced to add a Filtered Locale which would expose the "inheriting content" version of the Page to the frontend.

## Solution

I believe that `FluentFilteredExtension::augmentSQL()` should **not** be applied when reading mode is `DRAFT`.

### Force this outcome

I suspect that this might actually be the desired outcome for all projects - if so, we'll just add the reading mode check to `augmentSQL` all the time.

### Config setting

Let everyone decide whether it's required or not, and we'll add a new config value for `apply_filtered_locales_to_stage` (or something like that).

**Comment by robbieaverill** [comment]
Adding a config setting sounds safe enough and provides some flexibility here. I think I agree with you, it sounds a bit like versioned filtering in live mode on the frontend, whereas it always included draft when in the CMS.

If you're keen to make a PR that'd be smashing =)

**Comment by chrispenny** [comment]
Thanks, @robbieaverill!

Yup, definitely. Should be next week at the latest.
