### ISSUE TITLE
Allow caching and prepopulation for isLocalisedInStage

### ISSUE THREAD

**Issue by sminnee** [tractorcow-farm/silverstripe-fluent#467]
`FluentVersionedExtension::isLocalisedInStage()` is heavily used in the CMS, e.g. when rendering tree items.

In order to cut down on the query count on large sites, this value should be able to be cached and the cache prepopulated, as we do for page versions, and as I have recommended for Hierarchy::numChildren() in https://github.com/silverstripe/silverstripe-framework/issues/8379.

**Comment by sminnee** [comment]
One small challenge with this is that there's no extension hook for prepopulating more items. CMSMain may need an `onBeforeSiteTreeAsUL()` extension hook, or possibly a SiteTree singleton should carry this responsibility.

**Comment by tractorcow** [comment]
Yes that sounds about right @robbieaverill. I'd agree with such a cache addition.

We could have FluentSiteTree::prepopulate_localised_cache() as well.

**Comment by sminnee** [comment]
I've noted in https://github.com/silverstripe/silverstripe-framework/issues/8391 a refactoring of these caches to make it easier for modules such as fluent to plug into the system.

**Comment by ScopeyNZ** [comment]
I've been working on this today. It's going okay but pre-populating the cache is a little intense due to the fact that not all pages will be checked, but we can't really know what IDs to filter by on pre-pop.

Anyway. I'm addressing this with some `SELECT EXISTS` magic and I'll have a PR ready soon.

**Comment by sminnee** [comment]
Just get the results for all pages. If it's an optimised query it'll be a few ms even with 100,000 pages

**Comment by ScopeyNZ** [comment]
Yep!

**Comment by ScopeyNZ** [comment]
Oh I thought it was merged! Ha.

**Comment by robbieaverill** [comment]
I've pushed some tests to #468, I think it's good to go

**Comment by robbieaverill** [comment]
PR merged
