### ISSUE TITLE
Set up or move Scrutinizer to the farm

### ISSUE THREAD

**Issue by robbieaverill** [tractorcow-farm/silverstripe-fluent#484]
Hey @tractorcow!

Could you either move Scrutinizer from tractorcow to tractorcow-farm, or create a new one for it?

Cheers =)

**Comment by tractorcow** [comment]
Ah thanks for reminding me. I'll take care of it. Unless I forget, or don't have time.

**Comment by tractorcow** [comment]
ok setup https://scrutinizer-ci.com/g/tractorcow-farm/silverstripe-fluent/inspections/c96c2b63-db62-4014-8ea9-0d9f9743aa68

**Comment by robbieaverill** [comment]
Nice one, cheers!
