### ISSUE TITLE
we need more featueres in SS4

### ISSUE THREAD

**Issue by sunnysideup** [tractorcow-farm/silverstripe-fluent#492]
Hi,

I am working on features for Fluent in SS4.  I hope you can support this work (I will let you know when we are done).  We are working on:

a. ability to create, lock, edit, clear, etc... records per locale / class / table for better process in translation

b. providing users feedback on what areas still need to be translated

and more along those lines. 

Also, FYI: 

![image](https://user-images.githubusercontent.com/167154/48317985-83f53680-e65e-11e8-984c-dfca2694c5d5.png)

There are a few interesting modules for fluent, but they are all SS3

![image](https://user-images.githubusercontent.com/167154/48317991-93747f80-e65e-11e8-9c0c-a5a034923f4b.png)

(see ssmods.com / http://ssmods.com/#~(cfi~(Supports~(~(vtm~'4.*2a~ivl~'4.*2a)~(vtm~'5.*2a~ivl~'5.*2a))~Requires~(~(vtm~'fluent~ivl~'fluent)))~csr~(sdi~'desc~sct~'Created_U)))

**Comment by ScopeyNZ** [comment]
Sounds great! Are you working on adding this publicly and can point us to a branch? You might find there are some happy to help you out.

In the mean time, should we split the features into separate enhancement requests (if you image there'll be multiple different PRs) or do you want to manage development of these features elsewhere? I'm not quite sure how to triage this right now, it's not a bug report and it's not really a enhancement request either - just a show of intent to submit some work?

**Comment by sunnysideup** [comment]
We will publish as module(s) in the next week or so.  It would be great if you can add a link to it in docs or something like that so that people know about the modules. 

Just basically wanted to say: please support us adding value to this module by creating additional tools - and also let us know if others are doing the same / etc... so that we do not double up.

**Comment by ScopeyNZ** [comment]
Sure thing. Let us know here or on Slack when the modules are ready and we'll look at improving documentation around community modules. If there's a smaller module you can consider PRing it into here and then we'll be helping to maintain it! 🙂
