### ISSUE TITLE
Unable to get fluent localised field indicator to display on custom fields

### ISSUE THREAD

**Issue by kinglozzer** [tractorcow-farm/silverstripe-fluent#502]
I can’t seem to get Fluent’s inline “translatable” indicator to display on CMS fields that are added to `SiteTree` subclasses via `updateCMSFields()`. Example below, adding custom fields to `BlogPost` via an extension.

```php
class BlogPostExtension extends Extension
{
    private static $db = [
        'ShortTitle' => 'Varchar(40)'
    ];

    public function updateCMSFields(FieldList $fields)
    {
        $fields->insertAfter(
            'Title',
            TextField::create('ShortTitle', 'Short Title')
        );

        // This is the workaround I'm using
        $ext = new FluentExtension();
        $ext->setOwner($this->owner);
        $ext->updateCMSFields($fields);
    }
}
```

I assumed that it’d be possible to achieve this with `Before:`/`After:` blocks in YAML, but it seems not. I think it’s because `FluentExtension` is added to the base `SiteTree` class, but `BlogPostExtension` has to be specifically applied to the subclass `BlogPost`. When extension instances are constructed, they’re done so starting with the root class - meaning that it’s impossible to order subclass extension methods to run before parent classes.

So this specifically affects fields that are:

- Added to subclasses of `SiteTree` AND;
- Added via `getCMSFields()`

The site in question is Fluent 3.x and SilverStripe 3.7, but I believe the behaviour would be the same in 4.x - extensions are still constructed from root -> tip: https://github.com/silverstripe/silverstripe-framework/blob/4.3.0/src/Core/Extensible.php#L553

I did also try `BlogPostExtension extends FluentExtension`, but that completely broke the translation functionality on the site in question (no errors, it would just always use the English version). I assume that’s because it’s effectively applying `FluentExtension` twice if that approach is used on a page...

**Comment by robbieaverill** [comment]
I guess you have tried already, but there are some docs around this: https://github.com/tractorcow-farm/silverstripe-fluent/blob/3.8/docs/en/dataobjects.md#extensions

In that example you'd remove the FluentExtension I guess and replace it with your custom extension, ensuring that `parent::updateCMSFields($fields)` is called after your custom code

**Comment by kinglozzer** [comment]
> In that example you'd remove the FluentExtension I guess and replace it with your custom extension, ensuring that `parent::updateCMSFields($fields)` is called after your custom code

Yeah, is that possible with subclasses of `Page` though? Can you remove an extension from a subclass only?

**Comment by andrewnick** [comment]
I believe I'm having the same issue here. The indicators are not showing on fields added via Extensions (an extension on `CWP\CWP\PageTypes\EventPage`). I have tried adding `Before: '#fluentcms'` to the yml file where the extension is being added but that doesn't seem to make a difference. I also have tried it with `extends FluentExtension` but I'm getting ` Duplicate column name 'RecordID'` on a dev/build.

**Comment by kinglozzer** [comment]
@andrewnick If you need an ugly workaround, this is what we used in our SS3 site (untested against SS4):

```php
public function updateCMSFields(FieldList $fields)
{
    // Add fields as normal here

    $ext = new FluentExtension();
    $ext->setOwner($this->owner);
    $ext->updateCMSFields($fields);
}
```

**Comment by andrewnick** [comment]
Cheers @kinglozzer, that seems like a better approach that I went for (created a function on Field that can be added for each field). I'll have to give your approach a go.

**Comment by arthur-apanovics** [comment]
Thanks @kinglozzer for the workaround. We are using Fluent with Elemental where the base class (`BaseElement`) is already extended with Fluent, so if we want to create a custom extension we are forced to use the `FluentExtension` class which then complains about the base class already being extended by Fluent... 

+1 to the issue.

**Comment by tractorcow** [comment]
Fluent 5 has an option for this.

```
public function updateCMSFields(FieldList $fields)
{
    $this->owner->updateFluentLocalisedFields($fields);
}
```

This function is idempotent, and safe to call multiple times (In case you are scared of it running on multiple extensions.
