### ISSUE TITLE
Fluent localized fields cause the sort columns order to be changed

### ISSUE THREAD

**Issue by UndefinedOffset** [tractorcow-farm/silverstripe-fluent#507]
We have a object that is sorting first by a "Date" field, then the "Created", then the "Title" of the object. Fluent is added to this object and has the "Date" field included so it gets localized. When the query runs without Fluent the query has the correct order of `"Resource"."Date" DESC, "Resource"."Created" DESC, "Resource"."Title"`, but with Fluent enabled on the object the order becomes `""Resource"."Created" DESC, Resource"."Date" DESC, "Resource"."Title"`.

This seems to be due to the fact that Fluent is modifying the original query to include the `COALESCE` for the localized fields.

Seen on SilverStripe 4.3.2 with Fluent 4.2.0.

**Comment by robbieaverill** [comment]
Fixed in #508 - thanks @UndefinedOffset!
