### ISSUE TITLE
Can't click on the arrows of the select to choose a locale in the CMS UI

### ISSUE THREAD

**Issue by clarkepaul** [tractorcow-farm/silverstripe-fluent#514]
The icon is blocking the click event.
<img width="93" alt="Pasted_Image_6_04_19__9_04_AM" src="https://user-images.githubusercontent.com/555033/55653435-028b8400-584b-11e9-8065-1dab4fc5210e.png">
Using SS 4.3 Chrome

**Comment by robbieaverill** [comment]
Fixed in #520
