### ISSUE TITLE
Add detection for when FluentExtension is applied to a class hierarchy twice, which causes problems

### ISSUE THREAD

**Issue by JorisDebonnet** [tractorcow-farm/silverstripe-fluent#516]
## New issue

When FluentExtension is applied twice to a class hierarchy, e.g. to Page and to SiteTree, it will cause problems on dev/build and potentially other unpredictable places in the CMS.

We may be able to detect this (provided it doesn't have a performance hit of doing so) and throw an exception to pre-emptively warn users that their code is misconfigured.

---

## Original issue

I have been using Fluent for several years now, but my latest PageType refuses to build. I have updated to 4.2.0 to see whether it helps, but it does not. The problem is that the build tries to generate a unique index on the columns ("RecordID","Locale","RecordID","Locale"). No idea why it doubles those two columns!

(edit: see my comment below: I figured out why it's doing this)

Here is the relevant code: 
**mysite.yml**
```yml
FunkyDev\Collaborators\Collaborator:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
  translate:
    - 'Function'
    - 'Description'
```

**Collaborator.php**
```php
<?php

namespace FunkyDev\Collaborators;

use SilverStripe\AssetAdmin\Forms\UploadField;
use SilverStripe\Assets\Image;
use SilverStripe\Forms\EmailField;
use SilverStripe\Forms\TextField;

class Collaborator extends \Page
{
    private static $description = "Een OZG medewerker.";
    private static $singular_name = 'Medewerker';
    private static $plural_name = 'Medewerkers';
    private static $allowed_children = false;
    private static $default_parent = CollaboratorsOverview::class;
    private static $can_be_root = false;

    private static $table_name = 'Collaborator';
    private static $db = [
        'Function' => 'Varchar(255)',
        'Description' => 'Varchar(5000)',
        'Email' => 'Varchar(254)'
    ];
    private static $has_one = [
        'Photo' => Image::class,
    ];


    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        // irrelevant code
        return $fields;
    }
}
```

And here's what build/dev does:
```
Table Collaborator_Localised: created
Field Collaborator_Localised.ID: created as int(11) not null auto_increment
Field Collaborator_Localised.RecordID: created as int(11) not null default '0'
Field Collaborator_Localised.Locale: created as varchar(10) character set utf8 collate utf8_general_ci
Field Collaborator_Localised.Function: created as varchar(255) character set utf8 collate utf8_general_ci
Field Collaborator_Localised.Description: created as varchar(5000) character set utf8 collate utf8_general_ci
Index Collaborator_Localised.Fluent_Record: created as unique ("RecordID","Locale","RecordID","Locale")
Table Collaborator_Localised_Live: created
Field Collaborator_Localised_Live.ID: created as int(11) not null auto_increment
Field Collaborator_Localised_Live.RecordID: created as int(11) not null default '0'
Field Collaborator_Localised_Live.Locale: created as varchar(10) character set utf8 collate utf8_general_ci
Field Collaborator_Localised_Live.Function: created as varchar(255) character set utf8 collate utf8_general_ci
Field Collaborator_Localised_Live.Description: created as varchar(5000) character set utf8 collate utf8_general_ci
Index Collaborator_Localised_Live.Fluent_Record: created as unique ("RecordID","Locale","RecordID","Locale")
Table Collaborator_Localised_Versions: created
Field Collaborator_Localised_Versions.Version: created as int(11) not null default '0'
Field Collaborator_Localised_Versions.ID: created as int(11) not null auto_increment
Field Collaborator_Localised_Versions.RecordID: created as int(11) not null default '0'
Field Collaborator_Localised_Versions.Locale: created as varchar(10) character set utf8 collate utf8_general_ci
Field Collaborator_Localised_Versions.Function: created as varchar(255) character set utf8 collate utf8_general_ci
Field Collaborator_Localised_Versions.Description: created as varchar(5000) character set utf8 collate utf8_general_ci
Index Collaborator_Localised_Versions.Fluent_Record: created as unique ("RecordID","Locale","Version")
Table Collaborator_Localised: created
Field Collaborator_Localised.ID: created as int(11) not null auto_increment
Field Collaborator_Localised.RecordID: created as int(11) not null default '0'
Field Collaborator_Localised.Locale: created as varchar(10) character set utf8 collate utf8_general_ci
Field Collaborator_Localised.Function: created as varchar(255) character set utf8 collate utf8_general_ci
Field Collaborator_Localised.Description: created as varchar(5000) character set utf8 collate utf8_general_ci
Index Collaborator_Localised.Fluent_Record: created as unique ("RecordID","Locale","RecordID","Locale")
```
I just noticed it's creating the `Collaborator_Localised` table twice? Anyhow, both times it uses the double columns, as well as in the `_Live` version. I guess I don't need to paste the thrown Emergency, since obviously that index cannot be created.

**Comment by JorisDebonnet** [comment]
I just figured out that it's because Fluent automatically enables `FluentExtension` on `Page` already, and so with my config above, I'm trying to enable it twice. So removing the config line enabling `FluentExtension` on `Collaborator` fixed my issue.

Guess I'll leave this open in case you think it makes sense to either detect a 'double enabling' and gracefully handling that, or by somehow throwing a more clear error explaining what's wrong.

**Comment by JorisDebonnet** [comment]
Okay, it's not 100% fixed, but almost: the `_Localised` table is created correctly and everything works correctly, I can translate the fields I config'ed (Function and Description) --- but the only remaining issue is that the CMS does not show the "translatable" icon next to these fields. Even though they are.

![image](https://user-images.githubusercontent.com/3286264/56306959-1638c380-6144-11e9-926a-e3123d8ac88d.png)

![image](https://user-images.githubusercontent.com/3286264/56306894-fdc8a900-6143-11e9-9e6d-0d65861ca447.png)

**Comment by robbieaverill** [comment]
Have you tried putting your field definition logic inside `$this->beforeUpdateCMSFields()`?

**Comment by JorisDebonnet** [comment]
Ah my apologies, I had not taken that into account. So this issue reverts purely to "using the FluentExtension twice"... (once on the parent class, and once on the child class)

**Comment by robbieaverill** [comment]
That's OK! Yeah the problem with adding fluent twice has come up before. I think @tractorcow suggested we detect this internally and throw an exception to make it super obvious that it'll cause problems.

**Comment by robbieaverill** [comment]
I'll update the title of this issue to better reflect what we can do fix this

**Comment by tractorcow** [comment]
Yes please! I'm so sorry I haven't done this yet.

It'll solve a huge number of people's issues. :)

**Comment by tractorcow** [comment]
PR at https://github.com/tractorcow-farm/silverstripe-fluent/pull/553
