### ISSUE TITLE
Autotranslate

### ISSUE THREAD

**Issue by filiplikavcan** [tractorcow-farm/silverstripe-fluent#519]
We've created a module which integrates Silverstripe CMS with Google Translate API and then allows content editors to use automatic translation for every translatable field. Would you be interested in a PR or is it better to keep it separate? https://github.com/bratiask/silverstripe-autotranslate

**Comment by robbieaverill** [comment]
Hi @filiplikavcan, sounds like a very cool idea! I don't think this sounds like something that should be merged into fluent itself, but it's cool to see that you have created an addon module for fluent! You'd be welcome to add something to the readme of fluent to mention your module, if you'd like to do so. Thanks for raising this issue.
