### ISSUE TITLE
Cookie does not respect cookie_secure and is not HttpOnly

### ISSUE THREAD

**Issue by emteknetnz** [tractorcow-farm/silverstripe-fluent#534]
TractorCow\Fluent\Middleware\DetectLocaleMiddleware.php:201

The Cookie::set() call sets

a) secure to false
- seems like this should respect SilverStripe\Control\Session.$cookie_secure
- $cookie_secure is set to true by default on CWP for non-dev environments

b) httpOnly is false
- this is different from the default value of true in SilverStripe\Control\Cookie::set()
- seems as though this should be true, or we should be able to configure this in yml? (or maybe there's a reason why it's not httpOnly?)

**Comment by tractorcow** [comment]
That code is probably leftover from fluent 3 and should be updated. I suggest just PRing to respect the standard cookie settings.

I think we just copy Session, as you suggest.

```
$secure = Director::is_https($request) && $this->config()->get('cookie_secure');
```

We could possibly deprecate the existing `persist_cookie_path` (and others) and defer directly to Session settings.

**Comment by emteknetnz** [comment]
@tractorcow How about adding httpOnly?  Or does javascript need to access the cookie?

**Comment by tractorcow** [comment]
Ah, javascript used to use it... I don't remember if it still does.

**Comment by tractorcow** [comment]
PR at https://github.com/tractorcow-farm/silverstripe-fluent/pull/552
