### ISSUE TITLE
Wrong preview link (double URLSegment) in admin

### ISSUE THREAD

**Issue by AljosaB** [tractorcow-farm/silverstripe-fluent#538]
Preview link in admin is wrong for child pages. URLSegment for first level doubles. Example:

- root
  - test -> http://domain/test
    - child -> http://domain/test/test/child (double test)

![image](https://user-images.githubusercontent.com/1818329/62120220-77367280-b2c1-11e9-8adf-a44e47ae6f14.png)

Reverting changes from https://github.com/tractorcow-farm/silverstripe-fluent/commit/83f9fb975e3de9394f49703b3cc063829406ceb2 fixes it.

**Comment by tractorcow** [comment]
I've created a revert at https://github.com/tractorcow-farm/silverstripe-fluent/pull/539

**Comment by ScopeyNZ** [comment]
The revert is merged.
