### ISSUE TITLE
Remove fork?

### ISSUE THREAD

**Issue by chillu** [tractorcow-farm/silverstripe-fluent#540]
I'm doing contribution analytics over multiple years via gharchive.org. It takes into account repo renames by using the repo `id` instead. But in this case, we've *forked* https://github.com/tractorcow/silverstripe-fluent into https://github.com/tractorcow-farm/silverstripe-fluent. What was the purpose of that? Github has a "transfer ownership" function. The effect is that I can't track contributions to the original repo without workarounds, which is a pain when you're doing aggregate analytics over 100s to 1000s of repos. Admittedly, there will be other repos in there with the same issue, but this is one we're particularly interested in getting accurate data for (since it's a supported module)

Can anyone think of a way to resolve this without losing past contribution activity on either repo?

**Comment by robbieaverill** [comment]
AFAIK it was a transfer rather than a fork, but afterwards if Damian wants to contribute he would do so under his account fork, which would have the same URL as the original 😅

**Comment by chillu** [comment]
Oooooh right, it's *that* way around

![image](https://user-images.githubusercontent.com/111025/62177592-96083800-b399-11e9-8360-740fc1d6ad8b.png)

That explains why all the issues are on `tractorcow-farm`. Meaning the fork was created after the transfer, which means I can ignore the *new* https://github.com/tractorcow/silverstripe-fluent fork, All good, thanks for clarifying

**Comment by tractorcow** [comment]
Yeah sorry, it was so I could PR back safely. :) Otherwise I'm pushing all my PR branches upstream which is naughty. Even though I did it a few times accidentally haha.
