### ISSUE TITLE
Cant delete file with FluentFilteredExtension

### ISSUE THREAD

**Issue by sanderha** [tractorcow-farm/silverstripe-fluent#544]
Hi,

I've added `FluentFilteredExtension` to `File`. Now it seems I can no longer delete it via the assets admin.
It simple dissapears and reappears, and I get the "succesfully deleted" message. 
Note, the extension is applied by a module, not `/app`

Shouldnt it be possible to apply this extension to `File`?

**EDIT**
Removing the `UsesDeletePolicy` trait from `FluentFilteredExtension` solves this issue (not a solution of course). So it probably has something to do with that

**EDIT**
The issue only seems to exist when the File has Locales related to it

**EDIT**
This issue also seems to happen when applying `FluentFilteredExtension` to elements in the Elemental module

Fluent ^4.3
SS recipe cms ^4.3

**Comment by tractorcow** [comment]
I think we need to build some better docs for the deletion policy; Deletion is meant to occur only when the object is not visible in any locale (i.e. been deleted from each locale).

What we really need is some kind of separate "delete from this locale" and "delete from all locales" control, but that'd require a bit more thinking and effort.

**Comment by tractorcow** [comment]
My suggestion: Create a new factory for policies.

```yml
---
Name: fluentdelete
---
SilverStripe\Core\Injector\Injector:
  TractorCow\Fluent\Model\Delete\DeletePolicy:
    factory: MyApp\MyDeletePolicyFactory
```

Then do something simple like.

```php
public function create($service, array $params = [])
    {
        // Build policy
        $policy = new DeleteRecordPolicy();
        return $policy;
    }
```

**Comment by tractorcow** [comment]
@sanderha I've written up some developer docs on deletion policies at https://github.com/tractorcow-farm/silverstripe-fluent/pull/550

**Comment by sanderha** [comment]
Thats looks like a good idea, the docs you've written also make sense. I dont have the time to look at it right now, but certainly will do at some point soon
