### ISSUE TITLE
Question about. many_many_extraFields

### ISSUE THREAD

**Issue by martinviolet88** [tractorcow-farm/silverstripe-fluent#548]
Would it be possible to translate an many_many_extraFields via: private static $translate? I doubt it will, and i have not found any documentation about it, but it does not hurt to ask! Thanks.

**Comment by tractorcow** [comment]
No, but you can use many_many through, and apply versioned to that mapping object instead. :)

Since many_many_extraFields is un-extendable, it's unlikely that we will support localisation in fluent.
