### ISSUE TITLE
Improve documentation on FluentState

### ISSUE THREAD

**Issue by wernerkrauss** [tractorcow-farm/silverstripe-fluent#549]
There is no documentation on how to programmatically work with translations on pages, though some solutions are hidden in the issue section.

See #342, #542 

Today was a question on slack how to programmatically archive a page with all translations. Some snippets like this would be good.

**Comment by tractorcow** [comment]
Docs at https://github.com/tractorcow-farm/silverstripe-fluent/pull/551

**Comment by tractorcow** [comment]
Closed with #551
