### ISSUE TITLE
Backend control (CMS filter) is not showing

### ISSUE THREAD

**Issue by funfried** [tractorcow-farm/silverstripe-fluent#559]
Hello,

I've created two locales (German and English), I was able to create all the pages for the default locale (German), but I cannot switch to the other locale (English) because the dropdown is not appearing above the pages menu item like in the first screenshot in your readme.md file. Do I miss something?

I'm using Silverstripe version 4.4 and fluent 4.4.3

Kind regards,
Fabian

**Comment by tractorcow** [comment]
You may need to hard-refresh your page after creating a locale. If it doesn't appear can you check you have multiple locales saved, and share a screenshot?

E.g.

![image](https://user-images.githubusercontent.com/936064/67719376-98c90680-fa36-11e9-9a2c-5deb80f6b6fe.png)

![image](https://user-images.githubusercontent.com/936064/67719353-8bac1780-fa36-11e9-91b8-e4bf6c2cf66a.png)

**Comment by tractorcow** [comment]
Weird screenshot sizes huh. :D

**Comment by funfried** [comment]
Mine isn’t better 😅
![B0B8780C-15D3-48F2-9C6B-99E19DC9221B](https://user-images.githubusercontent.com/7093028/67723522-9f2a9480-f9dc-11e9-820e-bdf04fee8fff.png)

**Comment by tractorcow** [comment]
Maybe 4.4 changed something. I'll set up a site with that and retest.

**Comment by tractorcow** [comment]
I just installed a fresh 4.4 + fluent and it seems to work for me.

![image](https://user-images.githubusercontent.com/936064/67730456-fde22380-fa59-11e9-9912-1d0ee3e45eab.png)

**Comment by funfried** [comment]
Weird, do you know about any incompatible plugins? I installed some, like blog, userforms, spamprotection, onepage, ...

**Comment by funfried** [comment]
Ah, maybe I didn't copy all the files which are necessary for fluent, I cannot use composer directly on my webspace, so I installed it in a local directory and copied all the files from vendor/tractorcow/silverstripe-fluent to my webspace. Is there anything else I need to copy?

**Comment by tractorcow** [comment]
@funfried you might be missing a few files. 

I might suggest using something like https://github.com/heyday/beam if you are trying to synchronise a local copy of a site with a webserver.

**Comment by funfried** [comment]
Ok, I'll give it a shot, thanks.

**Comment by funfried** [comment]
It's finally working, you were right, I missed some files, thanks a lot!
