### ISSUE TITLE
Not possible to link an existing page in another locale as the translation for current page

### ISSUE THREAD

**Issue by conny-nyman** [tractorcow-farm/silverstripe-fluent#569]
Let's pretend we create one new page with the English locale and one page with Swedish locale, both pages are created as new SiteTree objects and they do not relate to each other. Currently it is not possible to link them afterwards so that they are translations for the same page/content, unless modifying the database directly.

This is not something that should occur under normal circumstances, but it would be nice to have a way to link an existing page in another locale to work as the translation for the current page.

**Comment by robbieaverill** [comment]
Like an "import from existing page" feature when creating a new version of a page in a locale?

To be honest, I don't think this is something we'll look at building right now. Contributions would be welcomed, however. You can work around this by copy and pasting the contents, or with a custom build task to modify the foreign keys as you've mentioned.

Thanks for reporting!
