### ISSUE TITLE
How to publish objects to a locale via code

### ISSUE THREAD

**Issue by muppsy007** [tractorcow-farm/silverstripe-fluent#575]
Existing site. Including the silverstripe blog module with almost 100 blog posts. Which are not represented in the sitetree as pages so note even batch actions are available. And manually loading up to 100 blog posts one at a time and hitting publish isn't going to fly.

So I need to create a task to do this. I've had a dig into the module code but don't see the write event that occurs when LOCALECOPYANDPUBLISH button is actioned. Can someone help me find the method call or snippet to do this on a per object basis in a BuildTask?

**Comment by robbieaverill** [comment]
It’s basically just publishRecursive() from versioned with a different label to try and improve the indication of what it’s doing in a fluent context. You can do this with a loop and a FluentState callback.

On another note, you can disable the lumberjack setting to hide blog posts in the site tree if you wanted to do that too.

Good luck!

**Comment by muppsy007** [comment]
@robbieaverill This needs to be a bit clearer. Different label? "and improve the indication of what's it's doing"? This is a rather abstract answer to a very specific question.

**Comment by robbieaverill** [comment]
Hey @muppsy007, the label “Publish” in the buttons for pages in the CMS is changed to “copy and publish” by fluent, but it’s underlying functionality is still `$page->publishRecursive()`. I hope that clears things up for you.

**Comment by muppsy007** [comment]
Thanks @robbieaverill. Will publishRecursive just pick up the default Locale and publish to that? Would one do something like this to select a different locale to interact with before calling it?

`FluentState::setLocale('es_MX`);`
