### ISSUE TITLE
Alternate href added to $MetaTags even if no localised version is published

### ISSUE THREAD

**Issue by lars-lemon8** [tractorcow-farm/silverstripe-fluent#582]
Fluent always adds alternate hrefs to the $MetaTags, even though there is no localised version in another language published.

How to reproduce :
1> Set frontend_publish_required to true in config
2> Add 2 locales
3> Add and publish page in the base locale, but do not publish it in the 2nd locale
4> Look at output of $MetaTags of base language page, it will add an alternate link containing just the base domain + locale, without a page segment. E.g. :  www.domain.com/en

**Comment by tractorcow** [comment]
That's true; We should limit the alternate tags to only versions that actually exist.

**Comment by lars-lemon8** [comment]
@tractorcow ,  FYI -> I cannot reproduce this behaviour in V5.0.0 

thanks all for the new release, Fluent is a life-safer !

**Comment by tractorcow** [comment]
Yep, looks like it was fixed in the above release.
