### ISSUE TITLE
SiteTree::get_by_link not working

### ISSUE THREAD

**Issue by sherlack** [tractorcow-farm/silverstripe-fluent#588]
Hi, I'm migrating a website from version 3 to 4 and for some reason SiteTree::get_by_link not working.

Is there a way to get the current sitetree page with the current locale?

I just to use something like this to get the sitetree object using the url segment.

$page = SiteTree::get_by_link("/en/faqs");

Any help will be appreciated.

Thanks

**Comment by tractorcow** [comment]
Hi @sherlack , if you omit the prefix, you might get the page, but it'll be in the current locale instead. E.g. `SiteTree::get_by_link('/faqs');`

**Comment by sherlack** [comment]
Hi @tractorcow , that worked! Thanks a bunch!

**Comment by tractorcow** [comment]
I'm glad that helped. :)
