### ISSUE TITLE
Unit tests Locale cache

### ISSUE THREAD

**Issue by mfendeksilverstripe** [tractorcow-farm/silverstripe-fluent#591]
When Unit test 1 populates the locale cache and Unit test 2 uses following setup:

```
protected function setUp()
{
    FluentState::singleton()->withState(function (FluentState $state): void {
        $state->setLocale('<some_locale>');

        parent::setUp();
    });
}
```

An issue with missing objects may occur due to interaction with Locale cache.

Note that wrapping `setUp` inside fluent state is really handy for unit tests that require all objects defined in the fixtures to use only one locale.

Fixed in https://github.com/tractorcow-farm/silverstripe-fluent/pull/590

**Comment by robbieaverill** [comment]
Thanks @mfendeksilverstripe !
