### ISSUE TITLE
Impossible to add fallback locale to different locale with the same Locale type

### ISSUE THREAD

**Issue by camelscript** [tractorcow-farm/silverstripe-fluent#595]
So I have multiple domains some of them have the same locales. For example:
- testsite-home.lv
  - Latvian (Main)
- testsite-office.lv
  - Latvian (Fallback to Main Latvian)
- testsite-garden.lv
  - Latvian (Fallback to Main Latvian)

It is impossible to select Latvian Fallback of Locale for testsite-office.lv testsite-garden.lv domain locales.

To fix this we can edit line at src/Model/Locale.php:251 :
` Locale::getCached()->exclude('Locale', $this->Locale)->map('ID', 'Title');`
to 
` Locale::getCached()->exclude('ID', $this->ID)->map('ID', 'Title');`

And then do tests if all is working well.

I don't know if this is a bug or you did not taught of such scenario, but it would be nice to have this function in master.

**Comment by tractorcow** [comment]
You know I've had this issue in the back of my mind... multiple locales with the same "Locale" value. The module itself actually assumes that each locale is is distinct, so I can imagine there will be a lot of issues you run into with this assumption.

I think the fact that you have managed to duplicate the Latvian locale across multiple locale dataobjects (and have it work, mostly) is fortunate, but risky. :)

We could change the behaviour of the locale identifier; Use $locale->ID as the unique indentifier, rather than $locale->Locale code. (i.e. FluentState would contain the ID as the state rather than code).

Here's an important question for you; Do each of your domains have different content? Are you using the locales to segment different content in the same language, rather than localising the same content in multiple languages?

Here's an opportunity here; Fluent 5.0 is in active development. If we want to support duplicate locales we could probably look at it here. I would want to know how widely demanded this feature is though.

**Comment by NightJar** [comment]
After a little discussion and clarification on slack, let me re-iterate here for posterity and to have a chance to re-clarify my understanding :)

Currently it is possible to have the same language multiple times on the site, but only if someone mis-uses the locale section (the Y's in `xx_YY`) e.g. en_NZ, en_AU, en_GB, en_US, en_CA, etc. This would be abuse with the context of the OP as all domains are in the same locale, but this could be a "work around".

You're proposing that it be possible to have e.g. en_NZ, en_NZ, en_NZ, etc. to more accurately match what the user is trying to do.

My thoughts on this is that while it might not get many responses in terms of demand, this might be a situation where it makes more sense to think about "How _intiuitive_ is this for the user?" - if it becomes much easier for someone to achieve their goals with what sounds like a code change that you've already planned and doesn't _sound_ (to me) to be much extra work as such... I feel like that in itself would be a big win :)

**Comment by robbieaverill** [comment]
@NightJar in your example you're showing different locales. Fluent deals with locales rather than languages, so there's nothing abusive about having a hierarchy of locales - that's what Fluent is designed for, and one of the ways it differs from Translatable.

**Comment by tractorcow** [comment]
@robbieaverill I think what he means is that the real-world language might actually not match the language we set in fluent, simply for the sake of avoiding a db uniqueness constraint. E.g. two NZ domains, but we pretend that the second is en_AU, when practically it should be en_NZ on both. This is the case of the Latvian example above. It's not an abuse in terms of the module / code, but is in terms of the SEO and user experience. :)

I.e. I'm a kiwi, not a trans-tasmanian, if that makes sense. :P

**Comment by tractorcow** [comment]
Another option is that we could, possibly, allow one locale to exist on multiple domains.

E.g. `locale >-- domain` becomes `locale >-< domain`.

The downside to this is that you can't customise content across domains in that one locale, but it does simplify the content authoring experience.

I would assume since @camelscript has a single locale in their site, they aren't actually doing any localisation.

To be honest, I might even go so far to suggest that in his case, he should look at subsites. Not sure if that's 100% going to solve his issues though. :)

**Comment by camelscript** [comment]
Thank you for all the opinions and solutions. Indeed we tried the locales en_NZ, en_AU, en_GB, en_US, en_CA, which kinda works for English, but not for for example Latvian. That's why I added this locale on the example, because it does not have the lv_NZ lv_AU lv_AU codes. Also it would be wrong from SEO to add such locales. Even if that would be en_AU but served as regular English. The browser might set up some settings for this locale etc. So this is not an option.


Also it is not an option to change that single line I mentioned in my initial message. I tried that and although i saved the record to DB Fluent itself relies on class::Locale->Locale field. I tried to change those functions to try to get it to work as I need, but quickly I realize it will be s a lot of coding so I abandoned the idea. 

> Here's an important question for you; Do each of your domains have different content?

Most of them have the same content, but in some cases I want to change single field. Let's say phone number or price tag for that particular locale. 
With a fallback locales it would be super easy to manage all the content and if I need I could just translate the page I need.


> Another option is that we could, possibly, allow one locale to exist on multiple domains.
> E.g. locale >-- domain becomes locale >-< domain.

I taught this myself that this could be a good option and could be a solution

Either way Fluent is a really good extension for localizing content and I use it on every project I need multiple locales. Great job!

**Comment by tractorcow** [comment]
It sounds like a situation where you might want some content bound to locale, others to the domain. Maybe a mix of both localisation + segmented content? It requires some thinking. :)

**Comment by tractorcow** [comment]
Maybe I should look at a hybrid fluent + subsites alternative. :P

**Comment by tractorcow** [comment]
Your example:


Locales:
 - Latvian

Domains:
 - office
 - home
- garden

Sites (replaces locale dropdown in CMS menu)
 - office latvian
 - home latvian
 - garden

Hypothetically you could add another locale, and assigning that locale to any domain would create a new "site".

**Comment by tractorcow** [comment]
The downside to this is that building this will break nearly every existing fluent site (even upgrading 4 -> 5) and require a lot of rewrite. I wonder if there's a midway solution that gets us most of the benefits...

**Comment by tractorcow** [comment]
@camelscript I wonder if I should just recommend you to use subsites for the time being; Fluent doesn't handle a single-locale model very well, but subsites should let you get away with it without too much trouble.

**Comment by camelscript** [comment]
I tried the option with Subsites + Fluent. Almost everything works except, Subsites does not know which is the default Locale for each domain. For now i have at least 4 Locales and not all of them needs to be added to all Subsites. So yes pretty complex. :)
I've got it working, but whenever i do 
` <% loop Locales %>`
it loops all the locales because as I said It does not know which Locale must be on which Subsite. But that's no problem ill filter them out manually. The other problem is that I can not go directly to testsite-home.lv because it returns 404 Not found. If I add language segment it works normally. Like this: testsite-home.lv/en or testsite-home.lv/lv. There is also a fix - I'll just add redirect from Page controller if user goes to page without language URL segment. 
This comment is just for your info and others who will try something similar in future.

That's it for now.

**Comment by tractorcow** [comment]
Well you only have one locale really :) You might get better value removing fluent and just using subsites. You will need to replace the locales menu with a subsites custom menu though.

If you can get it working for you that's what's important :)

**Comment by camelscript** [comment]
Actually we've grown to at least 4 locales now and I feel that there is more to come. :)

**Comment by tractorcow** [comment]
ok, if you have 4 different locales then keep using fluent :)

**Comment by camelscript** [comment]
No worries I'm not doing this to blame someone, but more to inform that there is such a scenario. You actually did a great job on building Fluent it is GOLD for multilingual pages. Works as a charm and in most cases does all what we could imagine. We even decide to switch 100% to SS over WP CMS because of SS have Fluent. And we don't want to mess with WP shi**y plugins. So thanks again to you. :)

**Comment by tractorcow** [comment]
In this case I will close this issue, but I'm happy to re-open if people feel like this should be re-evaluated.

At the moment I think fluent should avoid trying to complicate it's relational objects too much, so it will remain at the status quo for now (and upcoming 5.0).
