### ISSUE TITLE
Add a locale switcher to the page header in the CMS

### ISSUE THREAD

**Issue by adrhumphreys** [tractorcow-farm/silverstripe-fluent#596]
We've had some good feedback from users after implementing this:
![image](https://user-images.githubusercontent.com/10803137/74879194-800da380-53cd-11ea-91e7-087ccf9bff14.png)

Hovering over the icons shows a popup with the full name of the locale and then clicking it takes you to editing the page with the locale

Just wanted to check that this would be a welcome addition to the module?

**Comment by robbieaverill** [comment]
cc @silverstripeux

**Comment by clarkepaul** [comment]
Seems like a good addition and its clean. I don't see any reason why not, seems like one of those things where if it does clutter the page it could have a show/hide toggle added.

@adrhumphreys do you know if this site uses inheriting content or is it custom in each locale. I'm wondering if this would be a good place to try to show which pages inherit from the main locale here? 

Sidenote for future consideration:
When talking to the admins that use this UI they mentioned it would handy to be able to see all locales of a field/block at the same time because they don't like having to navigate to 14 different pages to edit each one individually, page loading is super slow and they lose there to place a lot, get confused etc. I can see how that would be an extreme time saver to edit all locales of a single field..

**Comment by adrhumphreys** [comment]
@clarkepaul originally we were going to add a section for inherited but not existing pages but the PO decided to just go down the route of showing the existence of the page on the locale and not consider inheritance at all, so for example the page could exist in MX above but there's no record of it in there

On the side note: We've had some troubles with this as we're using elemental but have kept the blocks entirely seperate per locale which means we can't have an author edit say the first carousel on the page and switch to editing it in another locale without taking a best guess as to if its the same block in the other locale. We ended up changing the locale switcher to take them to the edit link for the same page to avoid them accidentally editing the wrong block

**Comment by tractorcow** [comment]
Hi @adrhumphreys that's quite interesting that you've implemented this; I've actually been developing a feature equivalent behaviour in the `develop` branch.

The features implemented include a "Localisation" tab when editing a record.

![image](https://user-images.githubusercontent.com/936064/75119666-ce7eb300-56e9-11ea-8fef-49e2146acc06.png)

This view also is merged with the filtering behaviour, so you can toggle on and off records in individual locales.

Secondly, when editing a list of localised items, show a column with icons in the gridfield.

![image](https://user-images.githubusercontent.com/936064/75119672-e0f8ec80-56e9-11ea-98b9-08142da61787.png)

**Comment by tractorcow** [comment]
@clarkepaul 
>  I can see how that would be an extreme time saver to edit all locales of a single field..

The "copy to" button on that gridfield lets you copy between locales without having to switch. There's also a "copy to all locales" in the main actions.

The above screenshots need some more UX work though. "saved" probably should be "localised" and we could use some colour coding here.

**Comment by tractorcow** [comment]
@adrhumphreys I might try getting that "locales" column working with elemental. That might ease some of the issues with localised blocks. ;)

**Comment by tractorcow** [comment]
See https://github.com/tractorcow-farm/silverstripe-fluent/pull/577

**Comment by cwchong** [comment]
> @clarkepaul originally we were going to add a section for inherited but not existing pages but the PO decided to just go down the route of showing the existence of the page on the locale and not consider inheritance at all, so for example the page could exist in MX above but there's no record of it in there
> 
> On the side note: We've had some troubles with this as we're using elemental but have kept the blocks entirely seperate per locale which means we can't have an author edit say the first carousel on the page and switch to editing it in another locale without taking a best guess as to if its the same block in the other locale. We ended up changing the locale switcher to take them to the edit link for the same page to avoid them accidentally editing the wrong block

Hi @adrhumphreys, sorry for the necromancy but I am wondering if you can advise how you changed the locale switcher?
All references to that I can see seems to be baked in reactjs and does not seem easily overridden.

Thanks!

**Comment by adrhumphreys** [comment]
Hey @cwchong I just created my own field type as a `SilverStripe\Forms\DatalessField` and then shifted it up to sit above tabs on pages
