### ISSUE TITLE
Fluent breaks Versioned::get_including_deleted()

### ISSUE THREAD

**Issue by emteknetnz** [tractorcow-farm/silverstripe-fluent#600]
This is the code in fluent that's causing the breakage
https://github.com/tractorcow-farm/silverstripe-fluent/commit/0176dd41abaf579262927276fc89c1605b65c612

Broken unit test in silverstripe/cms when run in the context of silverstripe/cwp-recipe-kitchen-sink which includes fluent

https://github.com/silverstripe/silverstripe-cms/blob/4/tests/php/Controllers/CMSBatchActionsTest.php#L54

https://travis-ci.org/github/silverstripe/cwp-recipe-kitchen-sink/jobs/671091283

What's breaking in the unit test is that Versioned::get_including_deleted() is returns 0 results instead of 3.  Removing the newly added fluent function fixes this.

**Comment by emteknetnz** [comment]
@tractorcow I haven't dug too deeply into all the other travis failures, as there are 7 of them.  It seems likely though that it's also affecting something else in Versioned other than just ::get_including_deleted() since the CMSSiteTreeFilterTest is also failing, and that doesn't seem to use ::get_included_deleted()

My feeling on this is that unfortunately we're going to need to revert this pull request since it fixed one thing though it's broken some other things https://github.com/tractorcow-farm/silverstripe-fluent/pull/597

Here are travis links with the 'new' (broken) and 'old' (passing) versions of fluent

Travis with new (broken) version of fluent 0176dd4:
https://travis-ci.org/github/silverstripe/cwp-recipe-kitchen-sink/jobs/671091283

Travis with old (passing) version of fluent 0b86905:
https://travis-ci.org/github/creative-commoners/cwp-recipe-kitchen-sink/builds/671940137

**Comment by tractorcow** [comment]
Hi @emteknetnz I'm happy to revert that PR. I think it's wise in the mean time while we come up with a better long term solution that works for everyone. :)

**Comment by tractorcow** [comment]
Fix at https://github.com/tractorcow-farm/silverstripe-fluent/pull/601
