### ISSUE TITLE
SiteConfig gets duplicated

### ISSUE THREAD

**Issue by lekoala** [tractorcow-farm/silverstripe-fluent#603]
I'm not sure why, but my SiteConfig keep getting duplicated

I've implemented this yml fix
https://github.com/tractorcow-farm/silverstripe-fluent/commit/7e6d36d16b2dc2ee1ba437440bbca23648e73cec

but it doesn't seem to help the situation

I'll update this issue if I find why it's happening but it's really tricky to replicate

**Comment by tractorcow** [comment]
@lekoala can you show the SQL query that's generated by `SiteConfig::current_site_config()`? That will show what is going on under the hood. :)

**Comment by lekoala** [comment]
It seems pretty standard. What's odd is the content of the SiteConfig_Localised. I have two french translation and one in dutch, all linked to a different record. Not sure how I got there! 

1	2	fr_FR
2	1	fr_FR
3	3	nl_NL

> SELECT DISTINCT "SiteConfig"."ClassName", "SiteConfig"."LastEdited", "SiteConfig"."Created", "SiteConfig"."PrimaryColor", "SiteConfig"."SecondaryColor", "SiteConfig"."ThemeColor", "SiteConfig"."MaskColor", "SiteConfig"."HeaderFontFamily", "SiteConfig"."HeaderFontWeight", "SiteConfig"."BodyFontFamily", "SiteConfig"."BodyFontWeight", "SiteConfig"."CssTheme", "SiteConfig"."GoogleFonts", CASE WHEN "SiteConfig_Localised_fr_FR"."ID" IS NOT NULL THEN "SiteConfig_Localised_fr_FR"."EmailFooter" ELSE "SiteConfig"."EmailFooter" END AS "EmailFooter", "SiteConfig"."DefaultFromEmail", "SiteConfig"."ContactEmail", "SiteConfig"."FacebookPixelId", "SiteConfig"."Facebook", "SiteConfig"."Twitter", "SiteConfig"."LinkedIn", "SiteConfig"."Youtube", "SiteConfig"."Vimeo", "SiteConfig"."Flickr", "SiteConfig"."Instagram", "SiteConfig"."Pinterest", "SiteConfig"."GoogleAnalyticsCode", "SiteConfig"."GoogleAnalyticsWithoutCookies", "SiteConfig"."GoogleMapsApiKey", "SiteConfig"."ContactPhone", "SiteConfig"."ContactAddress", CASE WHEN "SiteConfig_Localised_fr_FR"."ID" IS NOT NULL THEN "SiteConfig_Localised_fr_FR"."ContactInfos" ELSE "SiteConfig"."ContactInfos" END AS "ContactInfos", "SiteConfig"."LegalName", "SiteConfig"."CompanyRegistrationNumber", "SiteConfig"."LegalCourt", CASE WHEN "SiteConfig_Localised_fr_FR"."ID" IS NOT NULL THEN "SiteConfig_Localised_fr_FR"."FooterText" ELSE "SiteConfig"."FooterText" END AS "FooterText", CASE WHEN "SiteConfig_Localised_fr_FR"."ID" IS NOT NULL THEN "SiteConfig_Localised_fr_FR"."Copyright" ELSE "SiteConfig"."Copyright" END AS "Copyright", "SiteConfig"."Title", "SiteConfig"."Tagline", "SiteConfig"."CanViewType", "SiteConfig"."CanEditType", "SiteConfig"."CanCreateTopLevelType", "SiteConfig"."LogoID", "SiteConfig"."IconID", "SiteConfig"."FaviconID", "SiteConfig"."ID", CASE WHEN "SiteConfig"."ClassName" IS NOT NULL THEN "SiteConfig"."ClassName" ELSE 'SilverStripe\\SiteConfig\\SiteConfig' END AS "RecordClassName", 'fr_FR' AS "Locale", CASE WHEN "SiteConfig_Localised_fr_FR"."ID" IS NOT NULL THEN 'fr_FR' ELSE NULL END AS "SourceLocale" FROM "SiteConfig" LEFT JOIN "SiteConfig_Localised" AS "SiteConfig_Localised_fr_FR" ON "SiteConfig"."ID" = "SiteConfig_Localised_fr_FR"."RecordID" AND "SiteConfig_Localised_fr_FR"."Locale" = ? LIMIT 1

**Comment by tractorcow** [comment]
From the above it looks like the issue is NOT the frontend_publish_required (although, if that was left on, it would have also caused this issue). There is yet another (possibly non-fluent) issue at play causing this.

The above does not even have a "WHERE" cause so it cannot be the reason the siteconfig is not being detected. It's just localising the various text fields without filtering them. =/

**Comment by lekoala** [comment]
Actually this seem to come from a faulty mysql client that exported somehow 3 records instead of one.  Not sure why, but not related to fluent anyway, so i'm closing the issue

**Comment by tractorcow** [comment]
That's good to know. ;)

Maybe fluent created the duplicate records, but after it was fixed, you just had to go back and manually clean up the duplicates?
