### ISSUE TITLE
Permissions Locales/Domains

### ISSUE THREAD

**Issue by Oliver996** [tractorcow-farm/silverstripe-fluent#605]
Are there any plans to add permissions for admin users to locales and domains in the future? Because i wasn't able to add canCreate, canView, canEdit or canDelete with an extension to it. 
But when I add them directly to the classes it works just fine. Is there a reason why you haven't added them or was there no need in your case?

**Comment by tractorcow** [comment]
Check out the develop branch it has a localise permission model :) It's not tagged yet sorry!

**Comment by tractorcow** [comment]
Details on how this works at the PR at https://github.com/tractorcow-farm/silverstripe-fluent/pull/594
