### ISSUE TITLE
Exclude translated fields in inherited page type?

### ISSUE THREAD

**Issue by derralf** [tractorcow-farm/silverstripe-fluent#607]
hi there,

I have a special page type "PartnerPage" where fields like Title, URLSegment and MenuTitle should not be translatable.

There the company name is entered and this is not different in German than in English. On the contrary: if it changes, I do not want to have to update it in all languages.

Is that possible?

The following did not produce any results:
(Title and MenuTitle were still translatable)

```
App\Model\PartnerPage:
  translate:
    - 'SubHeading'
    - 'Summary'
  field_exclude:
    - 'Title'
    - 'MenuTitle'
```

**Comment by tractorcow** [comment]
Hi @derralf ; URLSegment is on SiteTree, not on the subpage, so you can only turn on/off localisation for any field at that level.

A way to get around this is to create a separate field for title that is NOT translated.

Then you can override the PartnerPage like this

```

private static $db = [
    'PartnerTitle' => 'Varchar',
];

private static $field_exclude = [
    'PartnerTitle', // Won't be localised
];

public function getTitle()
{
// Ignore the base 'Title' field since that's localised
  return $this->getField('PartnerTitle');
}
```

I'm not sure if this will work for URLSegment but you can try

**Comment by tractorcow** [comment]
Just to clarify, adding field_exclude etc on fields that belong to the parent page (and not at the same level as this page) will have no effect.
