### ISSUE TITLE
Translation status and draft/published status is not visible in gridfields and userforms fields overview

### ISSUE THREAD

**Issue by Exeldur** [tractorcow-farm/silverstripe-fluent#616]
You can't see what is already translated in the gridfields and userforms fields overview. When Fluent is in use, you can no longer see the draft/published status in the gridfields .

Is there a way to display the translation status and i have to configure the gridfield differently in order for the draft/published status to work correctly in Fluent?

**Comment by tractorcow** [comment]
There sure is.

In your gridfield add the VisibleLocalesColumn gridfield component and you get a nice column with locale icons.

```php
$gridField->getConfig()->addComponent(new VisibleLocalesColumn());
```

![image](https://user-images.githubusercontent.com/936064/83072827-8d6cb500-a0c3-11ea-9733-80de24868823.png)

**Comment by tractorcow** [comment]
Please make sure you are on fluent 5.0 (alpha) to get this feature.

**Comment by tractorcow** [comment]
Red = not localised
Purple = localised, but not visible / published
Green = published and localised
