### ISSUE TITLE
Redundant copy locale actions fix (alpha 5)

### ISSUE THREAD

**Issue by mfendeksilverstripe** [tractorcow-farm/silverstripe-fluent#624]
# Redundant copy locale actions fix (alpha 5)

* `CopyLocaleAction` component is created as many times as there are locales available, see code snippet below (from `FluentExtension`):

```
foreach (Locale::getCached() as $locale) {
    $config->addComponents([
        new CopyLocaleAction($locale->Locale, true),
        new CopyLocaleAction($locale->Locale, false),
    ]);
}
```

* these components have slightly different UI but they all subscribe to the same action
* whenever either `copy to` or` copy from` action is executed, all of the components will execute the action

## Solution

Fixed in https://github.com/tractorcow-farm/silverstripe-fluent/pull/623

**Comment by tractorcow** [comment]
Good fix, I was worried about something in core, so I had attempted to fix it in the module.

GridField and GridField_ActionMenu both have different ways of invoking handleAction() on nested components:
 - GridField will only invoke the FIRST item that matches the action names
- GridField_ActionMenu will invoke ALL items that match the action names.


*GridField.php*

```php
    public function handleAlterAction($actionName, $arguments, $data)
    {
        $actionName = strtolower($actionName);

        foreach ($this->getComponents() as $component) {
            if ($component instanceof GridField_ActionProvider) {
                $actions = array_map('strtolower', (array) $component->getActions($this));

                if (in_array($actionName, $actions)) {
                    return $component->handleAction($this, $actionName, $arguments, $data);
                }
            }
        }

        throw new InvalidArgumentException(sprintf(
            'Can\'t handle action "%s"',
            $actionName
        ));
    }
```

*GridField_ActionMenu*


```php
    public function handleAction(GridField $gridField, $actionName, $arguments, $data)
    {
        foreach ($this->getItems($gridField) as $item) {
            $actions = [];
            if ($item instanceof GridField_ActionProvider) {
                $actions = $item->getActions($gridField);
            }

            if (in_array($actionName, $actions)) {
                $item->handleAction($gridField, $actionName, $arguments, $data);
            }
        }
    }
````

In our case, the code is in an action menu, so your fix is correct though. :) But it's worth checking in core I believe.

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow-farm/silverstripe-fluent/pull/623
