### ISSUE TITLE
Alpha 5 - new extension points for Copy locale action

### ISSUE THREAD

**Issue by mfendeksilverstripe** [tractorcow-farm/silverstripe-fluent#626]
# Alpha 5 - new extension points for Copy locale action

* adds useful extension points for the `copy locale` action
* no functional changes otherwise
* very useful for dealing with special handling of related objects which are localised by relation (indirectly), most notable example would be `Elemental`

## Solution

Fixed in https://github.com/tractorcow-farm/silverstripe-fluent/pull/625

**Comment by tractorcow** [comment]
Merged and tagged with https://github.com/tractorcow-farm/silverstripe-fluent/releases/tag/5.0.0-alpha9
