### ISSUE TITLE
Error in Preview Window at new created editors

### ISSUE THREAD

**Issue by danielschweiger** [tractorcow-farm/silverstripe-fluent#630]
I created a new user with content editor permissions and geht this error in the cms preview window with this user logged in:

<img width="380" alt="Bildschirmfoto 2020-07-04 um 21 53 46" src="https://user-images.githubusercontent.com/2277612/86520034-ea852480-be40-11ea-901e-63de008579c3.png">

```
[Emergency] Uncaught Error: Call to a member function getLocaleEditPermission() on null
GET /de/someurl/?stage=Stage&CMSPreview=1
Line 34 in /home/vagrant/somewhere.ss/vendor/tractorcow/silverstripe-fluent/src/Extension/FluentMemberExtension.php
```

```
$filtered = $groups->filterByCallback(function (Group $group) use ($locale) {
26             $localePermissions = $this->getLocalePermissionsForGroup($group);
27 
28             // Enabled if no locales selected
29             if (empty($localePermissions)) {
30                 return true;
31             }
32 
33             // Enabled if the current locale is selected, or disabled
34             return in_array($locale->getLocaleEditPermission(), $localePermissions);
35         });
36 
37         // Adjust group filter
38         $ids = $filtered->column('ID');
39         $groups = $groups->filter('ID', $ids ?: -1);
40     }
```
Also, I see not any translations in the Translations Tab of a page.

**Comment by tractorcow** [comment]
Oh, this could occur if Locale::getCurrentLocale() is null.

I don't suppose you could get the whole stacktrace?

I see you do have locales setup, but somehow it's not finding a current one.

I wonder why the current locale is null...

**Comment by danielschweiger** [comment]
@tractorcow 

`Trace
TractorCow\Fluent\Extension\FluentMemberExtension->TractorCow\Fluent\Extension\{closure}
call_user_func
DataList.php:491
SilverStripe\ORM\DataList->filterByCallback
FluentMemberExtension.php:35
TractorCow\Fluent\Extension\FluentMemberExtension->updateGroups
Extensible.php:468
SilverStripe\View\ViewableData->extend
Member.php:1308
SilverStripe\Security\Member->Groups
Permission.php:364
SilverStripe\Security\Permission::groupList
Permission.php:304
SilverStripe\Security\Permission::permissions_for_member
Permission.php:195
SilverStripe\Security\Permission::checkMember
Versioned.php:2215
SilverStripe\Versioned\Versioned::can_choose_site_stage
VersionedHTTPMiddleware.php:51
SilverStripe\Versioned\VersionedHTTPMiddleware->checkPermissions
VersionedHTTPMiddleware.php:28
SilverStripe\Versioned\VersionedHTTPMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
ExecMetricMiddleware.php:20
SilverStripe\Control\Middleware\ExecMetricMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
ConfirmationMiddleware.php:254
SilverStripe\Control\Middleware\ConfirmationMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
ConfirmationMiddleware.php:254
SilverStripe\Control\Middleware\ConfirmationMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
PasswordExpirationMiddleware.php:84
SilverStripe\Security\PasswordExpirationMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
BasicAuthMiddleware.php:68
SilverStripe\Security\BasicAuthMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
AuthenticationMiddleware.php:61
SilverStripe\Security\AuthenticationMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
CanonicalURLMiddleware.php:190
SilverStripe\Control\Middleware\CanonicalURLMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
HTTPCacheControlMiddleware.php:42
SilverStripe\Control\Middleware\HTTPCacheControlMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
ChangeDetectionMiddleware.php:28
SilverStripe\Control\Middleware\ChangeDetectionMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
FlushMiddleware.php:27
SilverStripe\Control\Middleware\FlushMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
RequestProcessor.php:66
SilverStripe\Control\RequestProcessor->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
SessionMiddleware.php:20
SilverStripe\Control\Middleware\SessionMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
AllowedHostsMiddleware.php:60
SilverStripe\Control\Middleware\AllowedHostsMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
TrustedProxyMiddleware.php:176
SilverStripe\Control\Middleware\TrustedProxyMiddleware->process
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}
HTTPMiddlewareAware.php:65
SilverStripe\Control\Director->callMiddleware
Director.php:369
SilverStripe\Control\Director->handleRequest
HTTPApplication.php:117
SilverStripe\Control\HTTPApplication::SilverStripe\Control\{closure}
call_user_func
HTTPApplication.php:136
SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}
HTTPMiddlewareAware.php:65
SilverStripe\Control\HTTPApplication->callMiddleware
HTTPApplication.php:137
SilverStripe\Control\HTTPApplication->execute
HTTPApplication.php:116
SilverStripe\Control\HTTPApplication->handle
index.php:24`

**Comment by tractorcow** [comment]
Oh, I see what's happening... it's possible that the versioning middleware is hitting the site BEFORE the fluent middleware can initialise the site state. We need to add a safety check that gracefully ignores missing locale.

**Comment by tractorcow** [comment]
Fix at https://github.com/tractorcow-farm/silverstripe-fluent/pull/631
