### ISSUE TITLE
Trying to get property 'Locale' of non-object

### ISSUE THREAD

**Issue by bumbus** [tractorcow-farm/silverstripe-fluent#633]
Hi,
 I ran into this issue in 5.0.0-alpha11 with a `DataObject` decorated with `FluentExtension` while trying to access the DetailForm in a `ModelAdmin`.

In my config I have this:

```
Khf\Seasons\TrainingSubject:
  frontend_publish_required: false
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
```

It seems to bail here:
https://github.com/tractorcow-farm/silverstripe-fluent/blob/5.0.0-alpha11/src/Extension/FluentExtension.php#L907

Is this somehow mal-configured or actually a bug?

Best Bumbus

**Comment by tractorcow** [comment]
Nope that's a bug in the code! Sorry about that.

@mfendeksilverstripe do you want to check this?

**Comment by mfendeksilverstripe** [comment]
Fixed in https://github.com/tractorcow-farm/silverstripe-fluent/pull/635
