### ISSUE TITLE
Silverstripe 4 Fluent and manymany uploadfield on Files

### ISSUE THREAD

**Issue by chromos33** [tractorcow-farm/silverstripe-fluent#641]
Quick Question cause either I am too blind to find the solution or there is not one.
But is it possible to make an Uploadfield with the Relation being many_many on File aware of Locale i.e. have the uploadfield in i.e. German Language have "have/display" different Files as the French or English one?

**Comment by tractorcow** [comment]
Sure can. Just make sure to use a has_many with the `through` option pointing to a mapping dataobject. Then add the `FluentIsolatedExtension` (new in fluent 5) to the mapping dataobject. It works without having to do any other configuration. :)
