### ISSUE TITLE
Publishing an error page sets the i18n locale in the CMS

### ISSUE THREAD

**Issue by GuySartorelli** [tractorcow-farm/silverstripe-fluent#642]
silverstripe/errorpage version 1.5.1
tractorcow/silverstripe-fluent version 4.5.0

When publishing an error page, the locale for the CMS is changed to the locale the page is published in. This results in fields being translated to that locale which may confuse some content authors.

Setting `enable_static_file` to `false` on the `ErrorPage` resolves this, as a workaround, but shouldn't be necessary.
I'm thinking this is a result of `i18n::set_locale($state->getLocale());` in `DetectLocaleMiddleware::process` during the request which is used to generate the static error page, and then not setting it back when returning to the CMS request.

Probably quite a low impact since it's only error pages and there is a (if not ideal) workaround.

**Comment by tractorcow** [comment]
This is a really good point...  it should affect 5.x as well.

This line will trigger.

```
        if ($locale && $state->getIsFrontend()) {
            i18n::set_locale($state->getLocale());
        }
```

We probably need to have some kind of FluentState::withState() to (somehow) wrap the publish.

I wouldn't be against `FluentState` backing up and restoring the `i18n` locale at the same time.

**Comment by tractorcow** [comment]
Oh, wait, easy solution.

In `DetectLocaleMiddleware` just wrap `Fluent::withState` around the below code.

```php
return FluentState::singleton()->withState(function() {
   // code from process goes here
});
```

We're already using the middleware pattern. :)

**Comment by GuySartorelli** [comment]
If #470 is still an issue, I suspect it will be impacted by this as well - most likely setting the locale for CMSPreview will currently cause the same issue described here.

**Comment by tractorcow** [comment]
Hi @GuySartorelli I've proposed a fix for this at https://github.com/tractorcow-farm/silverstripe-fluent/pull/644

**Comment by robbieaverill** [comment]
@tractorcow's fix is merged into the fluent 5.x release line

**Comment by GuySartorelli** [comment]
Is this only being fixed for 5.x?

**Comment by tractorcow** [comment]
We could back port it; But the good news is that the API breakage between 4.x and 5.x is VERY minimal. You should be able to upgrade without too much thought, if you want to try.

I will make a note to back port this fix later though. ;P

**Comment by tractorcow** [comment]
I've cherry picked that commit back to 4.5 @GuySartorelli

**Comment by GuySartorelli** [comment]
Awesome, thank you!

**Comment by tractorcow** [comment]
@GuySartorelli we found a regression in this fix. Please take care if you are using multi-domains. :) https://github.com/tractorcow-farm/silverstripe-fluent/pull/646/files?diff=unified&w=1

**Comment by GuySartorelli** [comment]
@tractorcow Thanks for the heads up!
