### ISSUE TITLE
Unpublishing a page in a non-default locale doesn't fall back to displaying default locale content.

### ISSUE THREAD

**Issue by GuySartorelli** [tractorcow-farm/silverstripe-fluent#643]
silverstripe/errorpage version 1.5.1
tractorcow/silverstripe-fluent version 4.5.0

After unpublishing a page in a locale, the most recently published copy of the page for that locale is still displayed in the front end, rather than falling back to the default locale.

**Example**
1. Page is published in default locale. It correctly displays on the front-end with only the default locale content regardless of what locale it is viewed in.
1. Page is _saved_ with different content in locale2. Only the default locale information is displayed on the front-end still.
1. Page is _published_ in locale2. Now, when viewing the page in locale2, this newly published content is displayed.
1. Page is _unpublished_ in locale2. On the front-end, the content that was published in step 3 is still displayed when viewing in locale2. This should be falling back to the default locale.
1. New content in Page is _saved but not published_ in locale2. On the front-end, the content that was published in step 3 is still displayed when viewing in locale2.
1. Page is once again _published_ in locale2. The front-end is once more in sync and displays the newly published content.

**Comment by tractorcow** [comment]
Quick questions:
 - Is frontend_publish_required left as default (true) or set to false (custom)?
- does the second locale have the default setup as a failover locale?

Technically the 'default locale' shouldn't really be setup as a failover unless at least one of the above are true;

There is also a distinction between content saved in the default locale, and the content saved to the base record; The configuration of frontend_publish_required will determine what is shown in the case of the specific locale being unpublished.

**Comment by GuySartorelli** [comment]
Oops! I didn't realise I had to explicitly set the default as a failover. That seemed like it should have been default behaviour, but I now see I'm wrong!
Setting the default as a failover for the second locale resolves it. Closing since it was user error.

**Comment by tractorcow** [comment]
thanks good to know 👍 

The old fluent module for SS3 did act that way, so it's not unfair that you would assume it would still be the same.
