### ISSUE TITLE
Domain redirects broken

### ISSUE THREAD

**Issue by bumbus** [tractorcow-farm/silverstripe-fluent#645]
Hi,
I am not sure, if this is a bug or configuration problem, but redirects to domains for a locale do not seem to work anymore.
I guess it happens since this commit:
https://github.com/tractorcow-farm/silverstripe-fluent/commit/d87e75287defa07f56bb920421669c8bd59cfef6

Best
Bumbus

**Comment by tractorcow** [comment]
Hm, I think I see the issue... the state "restore" probably is restoring it to a blank state, when it should only restore the original state if it was originally setup.

**Comment by tractorcow** [comment]
@bumbus is this the redirect when you use the locale menu to navigate to another region?

**Comment by tractorcow** [comment]
Also let me know if `SS_FLUENT_FORCE_DOMAIN="true"` in your .env config fixes this :)

**Comment by tractorcow** [comment]
Ah yes, this is the line of code that no longer works.

`FluentDirectorExtension.php`

```
        // Ensure InitStateMddleware is called here to set the correct defaultLocale
        Injector::inst()->create(InitStateMiddleware::class)->process($request, function () {
        });
```

Because the middleware is now non-mutable outside of the callback, this will no longer work as expected. ;)

**Comment by tractorcow** [comment]
Safest solution: Move the body of `FluentDirectorExtension::updateRules` to inside the callback; Rules will be setup correctly, but we still won't be mutating the state.

**Comment by tractorcow** [comment]
@bumbus can you please test https://github.com/tractorcow-farm/silverstripe-fluent/pull/646/files?diff=unified&w=1 and see if this fixes your issue?
