### ISSUE TITLE
Feature Request: Extension Point in FluentDirectorExtension

### ISSUE THREAD

**Issue by chromos33** [tractorcow-farm/silverstripe-fluent#654]
Quick Question/Feature Request, but is it possible to add an extension point ($this->extend("somefunction",[$parameters ...]));
here https://github.com/tractorcow-farm/silverstripe-fluent/blob/662fa1d0f8c9af51d23900d342521edc811277e5/src/Extension/FluentDirectorExtension.php#L97 so we can change the Locale i.e. when Fluent with Subsites module, so we can change that depending on HostURL and SubsiteDomains. 

So we don't need to use an Injector like here https://github.com/chromos33/subsitefluentextension/blob/main/src/Extensions/SubsiteFluentDirectorInjector.php to overwrite the updateRules function.

silverstripe/cms 4.6.0
silverstripe/framework 4.6.2
tractorcow/silverstripe-fluent            4.5.0
silverstripe/subsites                     2.3.3

**Comment by robbieaverill** [comment]
Go for it 👍

**Comment by tractorcow** [comment]
You could possibly extend FluentDirectorExtension and use injector to replace it (for the time being).

That doesn't mean adding an extension point is a bad idea, but that should get you an immediate option :)

**Comment by chromos33** [comment]
Merged into 5
