### ISSUE TITLE
Changelogs link in README.md results in 404 on 5.0.0

### ISSUE THREAD

**Issue by AlphaCactus** [tractorcow-farm/silverstripe-fluent#658]
1. Go to https://github.com/tractorcow-farm/silverstripe-fluent#documentation
2. Click Changelogs link https://github.com/tractorcow-farm/silverstripe-fluent/blob/5.0/CHANGELOG.md
Result: Github 404 error page

There is no CHANGELOG.md in 5.0.0 branch.

**Comment by tractorcow** [comment]
oops, thanks for that :D

**Comment by PatrickHollweck** [comment]
The link still results in a 404... Where can I find the current changelogs?

**Comment by tractorcow** [comment]
There is no changelog sorry, as I haven't really been maintaining them anymore.

I've removed the broken link.
