### ISSUE TITLE
Get used locale for partially translated content

### ISSUE THREAD

**Issue by spekulatius** [tractorcow-farm/silverstripe-fluent#664]
Hello @tractorcow,

I'm using fluent in a project which is (and always will be) partially translated. Some strings such as titles are translated while others aren't and will remain English.

I would like to know, from which locale a particular string was taken: The main locale or the fallback locale? Is this possible?

Some more background: This is needed as part of the project requires to have a different font for the localized strings only. Changing it on a per-locale level would lead to all texts -translated and fallback- using the new font. The `:lang`-selector could work, but for this, I would require to define the `lang` attribute on the HTML tags.

Cheers,
Peter

**Comment by tractorcow** [comment]
Yep, check out the "SourceLocale" field. It will show which locale the record was loaded from, whether the main locale, or the fallback one.

**Comment by tractorcow** [comment]
E.g. 

```html
<p>this record was loaded from the $SourceLocale.Locale locale</p>
```

**Comment by spekulatius** [comment]
Hey @tractorcow 

Thanks for replying. I'll try it out. Looks good - I'll close the issue and come back in case I got more questions.

Cheers,
Peter

**Comment by tractorcow** [comment]
Thanks glad I could answer your question @spekulatius :)
