### ISSUE TITLE
Can't get Fluent Website working after Upgrade

### ISSUE THREAD

**Issue by RoyalPulp** [tractorcow-farm/silverstripe-fluent#673]
Hello!! 

I am trying to upgrade a website with 4 Locales from SilverStripe 3 to SilverStripe 4.7

It is not the first time I do such an upgrade, but this site is larger and more complex.
Unfortunately I am running into more difficulties this time than with the other projects.

After enabling locales in the backend (on my local demo-server installation) , nothing worked in the frontend anymore but the Message: 

**The requested page could not be found.**

(I would really, really embrace the config-file approach to the locale-in-backend-definition . locale definition through config files like in the older versions, that's more SilverStripe style - and everything was clear and easy with that, you could just copy the config from locale to test server and to live server, and everything was ready to go!!)

Are there any helpful documents or "HowTo"s for fluent? I am really desperate - I really liked Fluent, but it costs soooooo much time (days, really!!)  to get it working in the upgrades

Help would be really appreciated
Thanks , Hnedrik

**Comment by tractorcow** [comment]
Hi @RoyalPulp sorry I have not responded to your message.

There are a lot of upgrade steps for upgrading from fluent 3 to 4/5. There are a few old PRs with users who have attempted to write up migration guides, but no official solution yet. :)

**Comment by RoyalPulp** [comment]
Hi @tractorcow ! 
Thank you, I solved that issue (had something to do with Fitered Locale on SiteTree) - and ran into a few other problems, when migrating the data from the  old localised Fields into the new Localised Tables, because the old Fallback strategy  (take from default if field empty) has somehow to be applied in sqlcode for the transfer...
