### ISSUE TITLE
RFC Fluent 6 support for framework 4.7 - fluent 5 keeps support for older framework versions

### ISSUE THREAD

**Issue by tractorcow** [tractorcow-farm/silverstripe-fluent#681]
As discussed at https://github.com/tractorcow-farm/silverstripe-fluent/pull/639#issuecomment-781030420

I don't really like the idea of fluent 5.1 forcing us to upgrade to framework 4.7, which is a pretty hefty upgrade (and has broken a few things of mine).

I suggest that we fork current 5 branch into 6, and ensure that fluent 5 works for all ^4 versions.

cc @mfendeksilverstripe  @chrispenny what do you think about this?

**Comment by mfendeksilverstripe** [comment]
@tractorcow Your suggestion makes sense, let's go with that 👍

**Comment by lars-lemon8** [comment]
Yeah, this sounds like a sane plan ! :-)    That many breaking changes in 4.7 huh ?

**Comment by tractorcow** [comment]
This is done. :)
