### ISSUE TITLE
v6 Elemental Interactions: Switching to a class containing an ElementalArea sets all localisations to base record

### ISSUE THREAD

**Issue by chrispenny** [tractorcow-farm/silverstripe-fluent#700]
## Set up

- `Page` is OotB Silverstripe `Page`
- `BlockPage` extends `Page`, and applies the `BlockPageExtension`

## Scenario

- I have a `Page` which is localised in all Locales.
- In one Locale, I change the `ClassName` from `Page` to `BlockPage`.
- This seems to result in all localisations pointing to the same `ElementalArea`.

A localised record is created for the locale I was on when I triggered the `ClassName` change, but no records are created for the others - so they end up pointing to the base record for their `ElementalArea`.

## Attempted solution (partial failure?)

I attempted to apply the `updateLocaliseSelect()` solution that is mentioned in the docs (though this is meant for frontend use, not CMS), but the result is infinite loading on the Elemental Area. This is maybe still useful though, if we could use this to trigger an author action to "create the Elemenal Area relationship" in some way.

```php
// Force this to apply, just for testing purposes
public function updateLocaliseSelect(string &$query, $table, $field, Locale $locale): void
{
    // We only want to modify fields in queries for the ElementalAreaID
    if ($field !== 'ElementalAreaID') {
        return;
    }

    // Disallow elemental data inheritance in the case that a localised page instance already exists
    $query = '"' . $table . '_Localised_' . $locale->getLocale() . '"."' . $field . '"';
}
```

![Screen Shot 2021-04-22 at 8 51 27 AM](https://user-images.githubusercontent.com/505788/115620320-21cdaf00-a349-11eb-97ea-7ba1c5808f00.png)

## Use case specific solution (success, but poor scalability)

To keep things moving for my project, I added the following to my `BlockPage`.

`onBeforeWrite()` I check to see if the `ClassName` changed.
`onAfterWrite()` I then make sure that each localisation has its own localised row with an ElementalArea assigned.

I do this `onAfterWrite()` so that it occurs after Elemental has "done it's things".

Might not be the prettiest, but it's working so far. However, I think this isn't scalable. It works fine for my specific use case where I know the field names/etc. Ideally you wouldn't have to think about it.

```php
private bool $requiresElementalAreaValidation = false;

protected function onBeforeWrite(): void
{
    parent::onBeforeWrite();

    // If the ClassName has changed, we we need to ensure our ElementalAreas are up to date
    $this->requiresElementalAreaValidation = $this->isChanged('ClassName');
}

protected function onAfterWrite(): void
{
    parent::onAfterWrite();

    $this->ensureElementalArea('ElementalAreaID', sprintf('%s_Localised', self::$table_name));
}

/**
 * If required, make sure that each localisation of this Page has its own unique ElementalArea for the specified
 * Table and Field
 *
 * @param string $elementalAreaFieldName
 * @param string $tableName
 * @throws ValidationException
 */
protected function ensureElementalArea(string $elementalAreaFieldName, string $tableName): void
{
    // This shouldn't ever happen (as this is called onAfterWrite()), but safety check anyway
    if (!$this->isInDB()) {
        return;
    }

    // We have specified that this is not required
    if (!$this->requiresElementalAreaValidation) {
        return;
    }

    /** @var string[] $locales */
    $locales = Locale::get()->column('Locale');

    // Loop through each Locale in our application
    foreach ($locales as $locale) {
        // This record is not localised in the requested Locale, so we don't need to do anything
        if (!$this->isDraftedInLocale($locale)) {
            continue;
        }

        // Check to see if there is already a localised row for this record
        $exists = SQLSelect::create(
            '*',
            $tableName,
            [
                'RecordID' => $this->ID,
                'Locale' => $locale,
            ]
        )->execute()->first();

        // This has already been localised, so we can assume that it has its own ElementalArea already
        if ($exists) {
            continue;
        }

        // There is no existing table row, so we can assume that this localisation does *not* have its own
        // ElementalArea, and so we should create one and assign it to a new localised table row
        $elementalArea = ElementalArea::create();
        $elementalArea->OwnerClassName = static::class;
        $elementalArea->write();

        // Insert the new localised table row
        SQLInsert::create(
            $tableName,
            [
                'RecordID' => $this->ID,
                'Locale' => $locale,
                $elementalAreaFieldName => $elementalArea->ID,
            ]
        )->execute();
    }
}
```

**Comment by tractorcow** [comment]
Oh, wow, that's a nasty edge case!

This is the case where each locale should have it's on blocks right?

**Comment by tractorcow** [comment]
@chrispenny try this:

- Add FluentIsolatedExtension to ElementalArea (forces each locale to have its own item)
- Add this yml

```
The\namespace\I\forgot\ElementalArea:
  apply_isolated_locales_to_byid: true
```

**Comment by tractorcow** [comment]
Note: Add apply_isolated_locales_to_byid to force the CMS to hide isolated related items from the CMS

**Comment by tractorcow** [comment]
This might work, might not.... we can tweak it if it doesn't though.

**Comment by tractorcow** [comment]
There's one issue in here though (base code)

```
    /**
     * Set all has_one relationships to an ElementalArea to a valid ID if they're unset
     *
     * @param array $elementalAreaRelations indexed array of relationship names that are to ElementalAreas
     * @return DataObject
     */
    public function ensureElementalAreasExist($elementalAreaRelations)
    {
        foreach ($elementalAreaRelations as $eaRelationship) {
            $areaID = $eaRelationship . 'ID';

            if (!$this->owner->$areaID) {
                $area = ElementalArea::create();
                $area->OwnerClassName = get_class($this->owner);
                $area->write();
                $this->owner->$areaID = $area->ID;
            }
        }
        return $this->owner;
    }
```

We need to change the check from :

```php
            if (!$this->owner->$areaID) {
```

to

```php
            if (!$this->owner->{$area}()->exists()) {
```

**Comment by chrispenny** [comment]
Thanks, @tractorcow ! I will give those a try.

**Comment by tractorcow** [comment]
ok, that's it, I'm going to officially add https://github.com/tractorcow-farm/silverstripe-fluent-elemental

**Comment by mfendeksilverstripe** [comment]
Fixed in https://github.com/tractorcow-farm/silverstripe-fluent/pull/717. This can be closed now @tractorcow @chrispenny
