### ISSUE TITLE
Fallbacks should only fallback to the correct locales

### ISSUE THREAD

**Issue by adrhumphreys** [tractorcow-farm/silverstripe-fluent#705]
Currently we have the following documentation for setting up fallbacks: https://github.com/tractorcow-farm/silverstripe-fluent/blob/5.0/docs/en/scenarios.md#content-inheritance-for-the-frontend

I think the extension should always be applied when `frontend_publish_required` is set to `false` or the config being updated. The reason for this is that I can't think of a situation where you would not want to only fallback to the locales you've selected as fallbacks

For example, if you have Maori, Japanese, Korea, and English then you could have a user viewing the Maori page and falling back to Japanese as it was the last written record. Then the next day it might fallback to English because that record got written to. Then the user refreshes the page and it's suddenly in Korean because someone updated the page

But maybe this is me mixing options and we need two configs one for fluent fallbacks (which I would assume is applied automatically when you have added a fallback (requiring no dev effort)) and then leaving `frontend_publish_required` alone?

**Comment by tractorcow** [comment]
The default is meant to have frontend_publish_required set to true for fallbacks to work properly; It was added as an option for users to want to customise this behaviour though. Literally, it treats "last written" as the global fallback; Not really the best scenario, but that's why it's set to true by default. :)

Options are: 
 - leave frontend_publish_required as true
 - set frontend_publish_required but make sure that all locales fallback up the chain to one "best" default

Just to confirm:

> For example, if you have Maori, Japanese, Korea, and English then you could have a user viewing the Maori page and falling back to Japanese as it was the last written record. Then the next day it might fallback to English because that record got written to. Then the user refreshes the page and it's suddenly in Korean because someone updated the page

You are assigning the "fallback" properly in the locales section right? You aren't just leaving it blank for all your locales?

**Comment by tractorcow** [comment]
I think I can see the problem,

What we really need is better granularity for frontend_publish_required:
 - true (must be published in this locale)
 - 'fallback' (must be published in this, or any fallback locale)
 - false (will fallback to last written record)

Alternatively:
 - true (must be published in this, or any fallback locale)
 - 'strict' (must be published in this exact locale)
 - false (will fallback to last written record)

**Comment by tractorcow** [comment]
@mfendeksilverstripe @chrispenny what do you think about the above?

**Comment by mfendeksilverstripe** [comment]
@tractorcow My preference would be to go with the true, strict and false options as true after this modification represents the most common case on our projects. Since this is v6 we can have a breaking change as this would not be backwards compatible but that's fine I think.

**Comment by chrispenny** [comment]
@tractorcow (CC: @mfendeksilverstripe @adrhumphreys)

In my mind `frontend_publish_required=true` equates to "strict", but I don't have a strong preference there. I think this would have the benefit of remaining backwards compatible though.

I do struggle to think of a good use case for allowing content to fall back to the "last written record", as it seems like it would be far too inconsistent an experience to be useful. The only area that I can think of that **might** warrant such a thing would be Assets. EG: You might decide that it's more important that the Asset is always available in all Locales, than it is for it to have the correct Title/etc. I'm not sold that this is a good enough reason to keep it around though.

At the moment I would be leaning towards:
* true (must be published in this locale)
* false (must be published in at least one fallback locale)

Maybe we could add a third options `'none'` to support base record fetching?

**Comment by tractorcow** [comment]
The only problem left is the "never written in default record" case, but other than that, yeah let's go with @chrispenny 's suggestion and keep true = strict. In 6.0 (unrelease) we can change the default from strict to fallback

**Comment by tractorcow** [comment]
So context of change:

requireSavedInLocale() can now return true, false, or `fallback`.

https://github.com/tractorcow-farm/silverstripe-fluent/blob/5.0/src/Extension/FluentExtension.php#L463-L468

This block of code will need to now conditionally handle true (as current behaviour), or `fallback`, which will be a conditional `IS NOT NULL` in ANY of the fallback locales.

**Comment by mfendeksilverstripe** [comment]
I'll add this change to my TODO list, I will put some time aside later this week for this :)

**Comment by tractorcow** [comment]
oh thanks @mfendeksilverstripe :)

**Comment by mfendeksilverstripe** [comment]
Raised a PR for this: https://github.com/tractorcow-farm/silverstripe-fluent/pull/711

**Comment by mfendeksilverstripe** [comment]
Fixed in the linked PR.
