### ISSUE TITLE
How to use with gorriecoe/silverstripe-linkfield

### ISSUE THREAD

**Issue by jrson83** [tractorcow-farm/silverstripe-fluent#716]
Hey,
I'm using the extension gorriecoe/silverstripe-linkfield and use two languages on the website, german and englisch. I have setup a CustomSiteConfig class in app\src\extensions which extends FluentExtension.

mysite.yml:
```
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - CustomSiteConfig
```

Inside the class I create a linkfield and use addFieldsToTab:

```
private static $has_one = [
  'TestLink' => Link::class,
];

...

$fields->addFieldsToTab(
            'Root.Main',
            [
                LinkField::create(
                    'TestLink',
                    'TestLink',
                    $this->owner
                )
            ]
        );
```

After extending the CustomSiteConfig class as FluentExtension and saving the configuration for every language, the translation worked for other fields but not the linkfield.

I added following to my mysite.yml:

```
gorriecoe\Link\Models\Link:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
gorriecoe\LinkField\LinkField:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
```

I removed the link for every language and created a new one. When i created the link on top of the link DataObject site, I can see the correct locale but when I create or delete a link it overwrites the link for the other language.

I'm using the extension also on a Page class and it is working fine. Did I anything wrong with the mysite.yml?

Thanks in advance.

Edit: I'm also using gorriecoe/silverstripe-menu and with the current configuration this works, just not for SiteConfig.

**Comment by tractorcow** [comment]
You need to explicitly translate has-one fields. you can add this to your code.

```php
private static $translate = [
  'TestLinkID',
];
```

I suggest to check if you need localised_copy with this also. https://github.com/tractorcow-farm/silverstripe-fluent/blob/5.0/docs/en/localised-copy.md

With localised copy, I think you can delete records on each locale without affecting other locales.

Then you're away :)

**Comment by jrson83** [comment]
Thank you very much, now it is working for the links. I guess I had to add then all other `private static $db = [ ... ]` variables to $translate after adding it.
