### ISSUE TITLE
Can't override GoogleSitemapController_sitemap.ss template

### ISSUE THREAD

**Issue by RoyalPulp** [tractorcow-farm/silverstripe-fluent#724]
Hi there!

in the "old " SS3 Version it was possible to override the template file GoogleSitemapController_sitemap.ss  (there it has been FluentSitemapController_sitemap.ss) 

I tried it with app/templates/GoogleSitemapController_sitemap.ss
and themes/[themename]/templates/GoogleSitemapController_sitemap.ss

... the sitemap uses only the vendor version.

How can I get the system to use my own template file?

thanks!!
Hendrik

**Comment by tractorcow** [comment]
Hi @RoyalPulp , you'll need to namespace your templates into the right folder.

app/templates/Wilr/GoogleSitemaps/Control/GoogleSitemapController_sitemap.ss is the right folder name .

Or themes/[themename]/templates/Wilr/GoogleSitemaps/Control/GoogleSitemapController_sitemap.ss

**Comment by RoyalPulp** [comment]
Thanks.. 
But, then I get an error: 
Fehler beim Laden des Stylesheets: Das Parsen eines XSLT-Stylesheets ist fehlgeschlagen.
(Cannot load/parse XSLT ...)

**Comment by tractorcow** [comment]
your custom xml in your custom template might be invalid maybe?

**Comment by RoyalPulp** [comment]
@tractorcow : Yes, thank You ! Missed or deleted one character in the process..  :)
