### ISSUE TITLE
Setup a new CI to run tests

### ISSUE THREAD

**Issue by mfendeksilverstripe** [tractorcow-farm/silverstripe-fluent#734]
# Setup a new CI to run tests

Travis.org is gone so we need to find another vendor / solution to run our CI pipeline.

**Comment by emteknetnz** [comment]
We're currently investigating migration from travis to github actions for Silverstripe modules.  We don't have a timeline for a stable implementation, though we've made a good start.  Feel free to experiment with using this - https://github.com/silverstripe/github-actions-ci-cd - feedback appreciated

**Comment by GuySartorelli** [comment]
This can be closed now ;p
