### ISSUE TITLE
Unpublish/draft language pages URL is still acessible

### ISSUE THREAD

**Issue by lucashfreitas** [tractorcow-farm/silverstripe-fluent#741]
Plugin version: 4.4.5.

Hi There,

We want to partially add content for another language but keep the pages unpublished until we have completely finished and are ready to push it live. 

I have a website that has English and Portuguese language version. English is the main language and we started to add content for Portuguese in some pages. Even-though those pages are unpublished and in draft mode, the URL **https://mywebsite.com/pt/page** is still accessible and google is indexing it. I was expecting that the website returns a 404 as the page is unpublished/draft in Portuguese. 

Due this it doesn't seem possible to keep two languages having one of them unpublished/draft. 

The solution for us was to remove completely all the Portuguese version for the pages, then if we access *https://mywebsite.com/pt/page**  it finally returns a 404 instead of loading the fallback english version. 

I tried to go to global language settings and disable the fallback but it didn't work, second language pages that are unpublished/draft can still be accessed by URL and the content fallbacks to english. 

Thanks,

**Comment by tractorcow** [comment]
Hi @lucashfreitas , you might find it easier to add the FluentFilteredExtension, which allows you to enable pages in each locale via a simple checkbox list.

![image](https://user-images.githubusercontent.com/936064/148832792-902a0256-134d-4118-9795-8852dc1d52b9.png)

You will need to update to fluent 5, but it's not a high-risk upgrade, and has minimal breakage from 4.x, but it'll give you much better functionality.

**Comment by lucashfreitas** [comment]
Hey @tractorcow  - thank you very much for the quick response. I will try it out!
