### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by mfendeksilverstripe** [tractorcow-farm/silverstripe-fluent#747]
# Update node version

We should probably update the node version. We're currently using `"node": "^6.x"` which is outdated.
Upgrading to at least `"node": "^10.x"` would be great.

**Comment by tractorcow** [comment]
Oh wow, 6.... that was a while ago.

**Comment by mfendeksilverstripe** [comment]
Fixed in https://github.com/tractorcow-farm/silverstripe-fluent/pull/766
