### ISSUE TITLE
Default language alias in URL

### ISSUE THREAD

**Issue by michalkleiner** [tractorcow-farm/silverstripe-fluent#75]
Hi Damian,

I was wondering if there was a way how to either filer or modify the URL generated for site's default language.

My settings involve 4 languages:
- English
- French
- Spanish
- Chinese

And 2 domains:
- example.com
- example.cn

Default language for example.en is English, default language for example.cn is Chinese and French and Spanish are under /fr/ and /es/ on example.en.

Is there a way how to get URLs without /en/ and /cn/ for default languages on both domains? If I have my settings right it works for homepages, but not for subpages.

http://example.com shows English homepage but all other pages are on http://example.com/en/page/subpage. My goal is to get them on http://example.com/page/subpage. 

I can 301 redirect them back to URLs without /en/ but I assume the links will still be created with /en/ in address, is that correct?

Hopefully I've explained it sufficiently.

Thanks,
Michal

**Comment by edgossage** [comment]
Sorry to jump in on a closed thread here, but I have the same issue and am not sure the above fix fulfils the original request. If I understood @michalkleiner correctly, the request was to remove the locale prefix for a default locale, regardless of how many locales sit under one domain. For example,

English site:
www.example.com
www.example.com/sub-page/
www.example.com/sub-page/sub-sub-page/

French site:
www.example.com/french/
www.example.com/french/sub-page/
www.example.com/french/sub-page/sub-sub-page/

German site:
www.example.com/german
www.example.com/german/sub-page/
www.example.com/german/sub-page/sub-sub-page/

Does this functionality exist?

**Comment by tractorcow** [comment]
> the request was to remove the locale prefix for a default locale, regardless of how many locales sit under one domain. For example,

The qualification I had for this was that that the domain under which this locale sit could have no other locales. As soon as you have more than one locale, you need a consistent prefix to distinguish locales, since you can no longer do it solely on the hostname.
