### ISSUE TITLE
Release 6.x.x

### ISSUE THREAD

**Issue by mfendeksilverstripe** [tractorcow-farm/silverstripe-fluent#761]
# Release 6.x.x

I'm happy with the current state on `6.x-dev` branch. Fluent 6 seems to be stable and is working fine on multiple projects. Additionally, the automated test suite is running now.

I'm keen on tagging a release candidate and try to eventually get `6.0.0` tag out.

Are there any blockers for this? Any pending issues that need to be resolved?

**Comment by mfendeksilverstripe** [comment]
@tractorcow @maxime-rainville Thoughts?

**Comment by tractorcow** [comment]
I was about to ask you :)

I had a feature branch I was working on for swapping locale for numeric id, but to be honest I don't really feel strongly enough about that to finish it, or even that we should go ahead.

so a 6.0.0 at status quo is fine by me.

**Comment by mfendeksilverstripe** [comment]
@tractorcow I've done the following:

- [x] created `6` branch
- [x] created `6.0` branch
- [x] created `6.0.0` tag
- [x] created a release for `6.0.0`

Is there anything else that needs to be done?

**Comment by maxime-rainville** [comment]
Just summarizing a Slack convo @mfendeksilverstripe had. We still ship version 4 in the sink ... so technically that's the version we support. We're looking at what work is needed to swap our support to v5 ... or v6 now.

But from our perspective that shouldn't block you from shipping version 6

**Comment by tractorcow** [comment]
I'm still actively working on v5 (since it doesn't require bleeding edge of framework), but I'm not doing much with 4 anymore. I highly suggest you jump your support to at least 5.
