### ISSUE TITLE
SilverStripe 5 compatibility

### ISSUE THREAD

**Issue by tractorcow** [tractorcow-farm/silverstripe-fluent#776]
Please comment on this ticket for adding features / development effort to go into the SilverStripe 5 compatibility roadmap.

This release will target fluent 7.0

**Comment by maxime-rainville** [comment]
FYI we created a temporary fork so we could devolped a CMS 5 compatible of Fluent: https://github.com/silverstripe/silverstripe-fluent

If OK with you, I'll just create a `7` branch from the `6` branch and open a PR from our fork.

Also part of our post beta work will be to draft an upgrade guide form CMS4 to CMS 5. That will involved some Fluent upgrade docs as well. @mfendeksilverstripe as already brief us.

**Comment by tractorcow** [comment]
Sure thing, I'll try to respond promptly to updates on github to make sure you get the feedback you need.

**Comment by tractorcow** [comment]
Master is now aliased to 7.x-dev, and I have updated the default branch + branch protection rules. 

https://github.com/tractorcow-farm/silverstripe-fluent/blob/master/composer.json

**Comment by tractorcow** [comment]
I created a preview PR to review the current diff https://github.com/tractorcow-farm/silverstripe-fluent/pull/777, but will close it once you have an updated PR for merge.

**Comment by maxime-rainville** [comment]
@tractorcow Thanks. I'll try to have the CMS Squad prioritise the work on Fluent this week.

**Comment by GuySartorelli** [comment]
New PR at https://github.com/tractorcow-farm/silverstripe-fluent/pull/779
