### ISSUE TITLE
TextCollector Task throws many Warnings

### ISSUE THREAD

**Issue by davejtoews** [tractorcow-farm/silverstripe-fluent#823]
### Module version(s) affected

5,6,7

### Description

The output of the i18nTextCollectorTask returns a number of warnings coming from this module. All are of two types:

```
[User Warning] Error concatenating localisation key
GET /dev/tasks/i18nTextCollectorTask?

Line 737 in /var/www/html/vendor/silverstripe/framework/src/i18n/TextCollection/i18nTextCollector.php
```
```
[User Notice] Missing localisation default for key Localisation
GET /dev/tasks/i18nTextCollectorTask

Line 815 in /var/www/html/vendor/silverstripe/framework/src/i18n/TextCollection/i18nTextCollector.php
```

Each instance of the second appears to be a direct result of the first. 

### How to reproduce

Run `/dev/tasks/i18nTextCollectorTask` with the environment set to `dev` or error reporting otherwise set to display PHP warnings.

### Possible Solution

The issue appears to be due to the use of the `__TRAIT__` magic constant w/in `_t()` function calls in FluentAdminTrait, FluentBadgeTrait and FluentObjectTrait. The backslashes in the fully namespaced trait name cannot be parsed.

It should be possible to resolve by replacing all instances of `__TRAIT__` with the string name of the class, or a function call which strips the namespace from the result.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by davejtoews** [comment]
This issue was originally flagged in #656 here: https://github.com/tractorcow-farm/silverstripe-fluent/issues/656#issuecomment-713666176

**Comment by GuySartorelli** [comment]
Sounds more like there's a bug in textcollector which should correctly support `__TRAIT__`.
