### ISSUE TITLE
Branching for CMS 6

### ISSUE THREAD

**Issue by maxime-rainville** [tractorcow-farm/silverstripe-fluent#826]
We're looking at starting development for CMS 6 and we've noticed the branching strategy for Fluent is a out of sync with the one we use in Silverstripe CMS core module.

- Core module no longer used master branches. The "next major branch" now use an integer value matching the expected release version.
- This allowed us to ditch the branch aliases in `composer.json`.
- Fluent currently has a `master` branch and a `7` branch.
  - Both of them target CMS 5.
  - They are currently out-sync
    - there's [commits in `7` not in `master`](https://github.com/tractorcow-farm/silverstripe-fluent/compare/master...7)
    - there's [commits in `master` not in `7`](https://github.com/tractorcow-farm/silverstripe-fluent/compare/7...master)
    - All the affected commits look like changes that could ship in a 7.1 minor.

## Proposed changes
1. Merged `master` back in `7`.
2. Make `7` the default branch.
3. Retarget any PRs directed at `master` to `7`.
4. Delete `master` branch.
5. Fork an `8` branch from `7` and set it up for CMS 6 development.

**Comment by maxime-rainville** [comment]
@tractorcow @mfendeksilverstripe I got enough permissions to do all the proposed changes ... except 2.

Assuming you don't have any objection or question, could one of you update the default branch to `7`. I can work with the CMS Squad to get the other 4 points done.

**Comment by mfendeksilverstripe** [comment]
hey @maxime-rainville I don't seem to have access for this either T_T

**Comment by tractorcow** [comment]
I've forked 8 but left default at 7. Does this suit, or should 8 be default now?

**Comment by maxime-rainville** [comment]
`8` won't be tagged until we release CMS 6 next year. Keeping `7` as the default branch for now is the best course of action.

I'll get the team to set up the `8` for CMS 6 development.

Thanks for your help, Damian! :pray:

**Comment by maxime-rainville** [comment]
@emteknetnz has addressed the outstanding points here.
