### ISSUE TITLE
Middleware is causing extra queries

### ISSUE THREAD

**Issue by lekoala** [tractorcow-farm/silverstripe-fluent#828]
### Module version(s) affected

7.0.0

### Description

Here is a debugbar screenshot

![image](https://github.com/tractorcow-farm/silverstripe-fluent/assets/250762/6fd911df-5d1b-45e1-b1af-02658aef0ca8)

We see that we have two SHOW FULL FIELDS. One from the Domain class (even if you have a single domain and not using domain mode) and one for the Locale table (due to the databaseIsReady check). 

In many cases, this should not be made PER REQUEST. It could be useful to avoid errors in case the database is not available, but it should not lead to extra queries being applied for every request.

Unused features should not cause extra queries either.

### How to reproduce

Install the module
Install the debugbar
Check that indeed we have these queries

### Possible Solution

- Have a env var to disable domain feature if not used and avoid extra queries
- Allow forcing locale per dev config, instead of db config
- Take an optimistic approach for db availability and avoid extra checks per requests

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by tractorcow** [comment]
You could update the check for CacheableModel::databaseIsReady() to only run during dev/build, and return "true" hard coded otherwise. That's the only time it needs to know about the build status.

**Comment by tractorcow** [comment]
Fix at https://github.com/tractorcow-farm/silverstripe-fluent/pull/831

**Comment by lekoala** [comment]
even better :-)

**Comment by tractorcow** [comment]
There was a regression in my fix but those have been resolved now. 6 and 7 branches have the updated fix in them merged up.

**Comment by lekoala** [comment]
great thank you!

**Comment by tractorcow** [comment]
Sorry I didn't merge up into 7.0.0 branch, didn't make it into RC release, but it's not an urgent fix :)
