### ISSUE TITLE
Integrate Spanish translation

### ISSUE THREAD

**Issue by juanjosegzl** [tractorcow-farm/silverstripe-fluent#843]
### Description

Hola, some time ago I translated the strings to Spanish in [transifex](https://app.transifex.com/silverstripe/silverstripe-fluent/language/es/).

I wonder what are the next steps to integrate the translation to be released?

I'm open to submit the required changes

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

**Comment by GuySartorelli** [comment]
These are pulled through periodically - I think currently it's every 3 months.
The PR for this has just come through. See https://github.com/tractorcow-farm/silverstripe-fluent/pull/844.

We're tracking it internally with https://github.com/silverstripe/.github/issues/234 so I'll close this issue.
